export function buildRuntimeKeyPageLoaders(args) {
  const {
    pageSignature,
    auditFrom,
    auditTo,
    reportOwner,
    reportDepartment,
    reportTimezone,
    auditRole,
    reportCurrency,
    canViewReports,
    reportExportStatusFilter,
    reportExportJobsPage,
    reportExportJobsSize,
    loadTasks,
    loadWorkbenchToday,
    loadReports,
    loadReportExportJobs,
    auditUser,
    auditAction,
    exportStatusFilter,
    exportJobsPage,
    exportJobsSize,
    canViewAudit,
    loadAudit,
    loadExportJobs,
    loadPermissionMatrix,
    loadPermissionConflicts,
    canManageUsers,
    loadAdminUsers,
    loadTenants,
    canManageSalesAutomation,
    loadLeadAssignmentRules,
    loadAutomationRulesV1,
    approvalTaskStatus,
    approvalOverdueOnly,
    approvalEscalatedOnly,
    notificationStatusFilter,
    notificationPage,
    notificationSize,
    loadApprovalTemplates,
    loadApprovalStats,
    loadApprovalInstances,
    loadApprovalTasks,
    loadNotificationJobs,
    loadDesignerTemplates,
  } = args

  return {
    dashboard: {
      signature: pageSignature(
        'dashboard',
        {
          from: auditFrom,
          to: auditTo,
          owner: reportOwner,
          department: reportDepartment,
          timezone: reportTimezone,
          role: auditRole,
          currency: reportCurrency,
          canViewReports,
          reportExportStatusFilter,
          reportExportJobsPage,
          reportExportJobsSize,
        },
        1,
        0,
      ),
      canRun: () => true,
      run: () =>
        Promise.all([
          loadTasks(),
          loadWorkbenchToday(),
          canViewReports ? loadReports() : Promise.resolve(null),
          canViewReports ? loadReportExportJobs(reportExportJobsPage, reportExportJobsSize) : Promise.resolve(null),
        ]),
    },
    reports: {
      signature: pageSignature(
        'reports',
        {
          from: auditFrom,
          to: auditTo,
          owner: reportOwner,
          department: reportDepartment,
          timezone: reportTimezone,
          role: auditRole,
          currency: reportCurrency,
          canViewReports,
          reportExportStatusFilter,
          reportExportJobsPage,
          reportExportJobsSize,
        },
        1,
        0,
      ),
      canRun: () => canViewReports,
      run: () => Promise.all([loadReports(), loadReportExportJobs(reportExportJobsPage, reportExportJobsSize)]),
    },
    audit: {
      signature: pageSignature(
        'audit',
        {
          user: auditUser,
          role: auditRole,
          action: auditAction,
          from: auditFrom,
          to: auditTo,
          exportStatusFilter,
          exportJobsPage,
          exportJobsSize,
        },
        1,
        0,
      ),
      canRun: () => canViewAudit,
      run: () => Promise.all([loadAudit(), loadExportJobs(exportJobsPage, exportJobsSize)]),
    },
    permissions: {
      signature: pageSignature('permissions', {}, 1, 0),
      canRun: () => true,
      run: () => Promise.all([loadPermissionMatrix(), loadPermissionConflicts()]),
    },
    usersAdmin: {
      signature: pageSignature('usersAdmin', {}, 1, 0),
      canRun: () => canManageUsers,
      run: () => Promise.all([loadAdminUsers(), loadTenants()]),
    },
    salesAutomation: {
      signature: pageSignature('salesAutomation', {}, 1, 0),
      canRun: () => canManageSalesAutomation,
      run: () => Promise.all([loadLeadAssignmentRules(), loadAutomationRulesV1()]),
    },
    adminTenants: {
      signature: pageSignature('adminTenants', {}, 1, 0),
      canRun: () => canManageUsers,
      run: () => loadTenants(),
    },
    approvals: {
      signature: pageSignature(
        'approvals',
        {
          taskStatus: approvalTaskStatus,
          overdueOnly: approvalOverdueOnly,
          escalatedOnly: approvalEscalatedOnly,
          notificationStatusFilter,
          notificationPage,
          notificationSize,
        },
        1,
        0,
      ),
      canRun: () => true,
      run: () =>
        Promise.all([
          loadApprovalTemplates(),
          loadApprovalStats(),
          loadApprovalInstances(),
          loadApprovalTasks(),
          loadNotificationJobs(notificationPage, notificationSize),
        ]),
    },
    reportDesigner: {
      signature: pageSignature('reportDesigner', {}, 1, 0),
      canRun: () => true,
      run: () => loadDesignerTemplates(),
    },
  }
}
