function buildRuntimeShellProps({
  auth,
  hasAuthToken,
  isAuthRoute,
  location,
  apiContext,
  lang,
  setLang,
  t,
  navigate,
  submitLogin,
  submitRegister,
  loginForm,
  setLoginForm,
  registerForm,
  setRegisterForm,
  formErrors,
  setFormErrors,
  submitSsoLogin,
  ssoConfig,
  ssoForm,
  setSsoForm,
  oidcAuthorizing,
  startOidcLogin,
  loginError,
  navGroups,
  activePage,
  onNavigate,
  onPrefetch,
  performLogout,
  devPerfEnabled,
  perfMetrics,
  currentLoaderKey,
  lastRefreshReason,
  currentPageSignature,
  currentSignatureHit,
  recentWorkbenchJump,
  domainLoadSource,
  copyPerfSnapshot,
  lastPerfSnapshotAt,
  markRenderCommit,
}) {
  return {
    authShellProps: {
      auth: !hasAuthToken || isAuthRoute ? null : auth,
      locationPathname: location.pathname,
      apiContext,
      lang,
      setLang,
      t,
      navigate,
      submitLogin,
      submitRegister,
      loginForm,
      setLoginForm,
      registerForm,
      setRegisterForm,
      formErrors,
      setFormErrors,
      submitSsoLogin,
      ssoConfig,
      ssoForm,
      setSsoForm,
      oidcAuthorizing,
      startOidcLogin,
      loginError,
    },
    appShellProps: {
      auth,
      navGroups,
      activePage,
      onNavigate,
      onPrefetch,
      performLogout,
      t,
      dev: devPerfEnabled,
      perfMetrics,
      currentLoaderKey,
      lastRefreshReason,
      currentPageSignature,
      currentSignatureHit,
      recentWorkbenchJump,
      domainLoadSource,
      copyPerfSnapshot,
      lastPerfSnapshotAt,
      markRenderCommit,
    },
  }
}

export { buildRuntimeShellProps }
