import { normalizeDateFormat } from './routeConfig'

export function buildRuntimeDomainActionsConfig({
  auth,
  lang,
  role,
  t,
  canViewOpsMetrics,
  canManagePermissions,
  canViewReports,
  handleError,
  refreshPage,
  state,
  loaders,
}) {
  return {
    leadImport: {
      auth,
      lang,
      t,
      canViewOpsMetrics,
      handleError,
      refreshPage,
      setLeadImportJob: state.setLeadImportJob,
      setLeadImportFailedRows: state.setLeadImportFailedRows,
      setLeadImportStatusFilter: state.setLeadImportStatusFilter,
      setLeadImportPage: state.setLeadImportPage,
      setLeadImportSize: state.setLeadImportSize,
      setLeadImportExportStatusFilter: state.setLeadImportExportStatusFilter,
      setLeadImportExportPage: state.setLeadImportExportPage,
      setLeadImportExportSize: state.setLeadImportExportSize,
    },
    pageActions: {
      auth,
      lang,
      role,
      t,
      normalizeDateFormat,
      setError: state.setError,
      handleError,
      assignmentRuleForm: state.assignmentRuleForm,
      setAssignmentRuleForm: state.setAssignmentRuleForm,
      loadLeadAssignmentRules: loaders.loadLeadAssignmentRules,
      automationRuleForm: state.automationRuleForm,
      setAutomationRuleForm: state.setAutomationRuleForm,
      loadAutomationRulesV1: loaders.loadAutomationRulesV1,
      canManagePermissions,
      permissionRole: state.permissionRole,
      pendingPack: state.pendingPack,
      setPendingPack: state.setPendingPack,
      setPermissionPreview: state.setPermissionPreview,
      setPermissionMatrix: state.setPermissionMatrix,
      loadPermissionConflicts: loaders.loadPermissionConflicts,
      setAdminUsers: state.setAdminUsers,
      setInviteResult: state.setInviteResult,
      setInviteForm: state.setInviteForm,
      inviteForm: state.inviteForm,
      loadAdminUsers: loaders.loadAdminUsers,
      approvalTemplateForm: state.approvalTemplateForm,
      setApprovalTemplateForm: state.setApprovalTemplateForm,
      setApprovalTemplates: state.setApprovalTemplates,
      loadApprovalTemplates: loaders.loadApprovalTemplates,
      loadApprovalStats: loaders.loadApprovalStats,
      loadApprovalInstances: loaders.loadApprovalInstances,
      loadApprovalTasks: loaders.loadApprovalTasks,
      approvalInstanceForm: state.approvalInstanceForm,
      setApprovalInstanceForm: state.setApprovalInstanceForm,
      approvalActionComment: state.approvalActionComment,
      setApprovalActionComment: state.setApprovalActionComment,
      approvalTransferTo: state.approvalTransferTo,
      setApprovalTransferTo: state.setApprovalTransferTo,
      setApprovalActionResult: state.setApprovalActionResult,
      approvalPendingTaskIds: state.approvalPendingTaskIds,
      setApprovalPendingTaskIds: state.setApprovalPendingTaskIds,
      approvalDetail: state.approvalDetail,
      loadApprovalDetail: loaders.loadApprovalDetail,
      loadNotificationJobs: loaders.loadNotificationJobs,
      setSelectedNotificationJobs: state.setSelectedNotificationJobs,
      notificationJobs: state.notificationJobs,
      selectedNotificationJobs: state.selectedNotificationJobs,
      notificationStatusFilter: state.notificationStatusFilter,
      notificationPage: state.notificationPage,
      notificationSize: state.notificationSize,
      tenantForm: state.tenantForm,
      setTenantForm: state.setTenantForm,
      setLastCreatedTenant: state.setLastCreatedTenant,
      loadTenants: loaders.loadTenants,
      setTenantRows: state.setTenantRows,
      refreshPage,
      hasInvalidAuditRange: loaders.hasInvalidAuditRange,
      setAuditRangeError: state.setAuditRangeError,
      auditUser: state.auditUser,
      auditRole: state.auditRole,
      auditAction: state.auditAction,
      auditFrom: state.auditFrom,
      auditTo: state.auditTo,
      reportOwner: state.reportOwner,
      reportDepartment: state.reportDepartment,
      reportTimezone: state.reportTimezone,
      reportCurrency: state.reportCurrency,
      canViewReports,
      reportDesignerForm: state.reportDesignerForm,
      setReportDesignerForm: state.setReportDesignerForm,
      setDesignerRunResult: state.setDesignerRunResult,
      loadApprovalTemplateVersions: loaders.loadApprovalTemplateVersions,
    },
  }
}
