export function buildRuntimeStateContextsAuthUi(runtime) {
  return {
    authCtx: {
      auth: runtime.auth,
      loginError: runtime.loginError,
      setLoginError: runtime.setLoginError,
      loginForm: runtime.loginForm,
      setLoginForm: runtime.setLoginForm,
      mfaChallengeId: runtime.mfaChallengeId,
      setMfaChallengeId: runtime.setMfaChallengeId,
      ssoConfig: runtime.ssoConfig,
      setSsoConfig: runtime.setSsoConfig,
      ssoForm: runtime.ssoForm,
      setSsoForm: runtime.setSsoForm,
      oidcAuthorizing: runtime.oidcAuthorizing,
      setOidcAuthorizing: runtime.setOidcAuthorizing,
      sessionBootstrapping: runtime.sessionBootstrapping,
      setSessionBootstrapping: runtime.setSessionBootstrapping,
      formErrors: runtime.formErrors,
      setFormErrors: runtime.setFormErrors,
    },
    uiCtx: {
      loading: runtime.loading,
      error: runtime.error,
      setError: runtime.setError,
      crudErrors: runtime.crudErrors,
      setCrudErrors: runtime.setCrudErrors,
      crudFieldErrors: runtime.crudFieldErrors,
      setCrudFieldErrors: runtime.setCrudFieldErrors,
      activePage: runtime.activePage,
      setActivePage: runtime.setActivePage,
      currentLoaderKey: runtime.currentLoaderKey,
      setCurrentLoaderKey: runtime.setCurrentLoaderKey,
      lastRefreshReason: runtime.lastRefreshReason,
      setLastRefreshReason: runtime.setLastRefreshReason,
      currentPageSignature: runtime.currentPageSignature,
      setCurrentPageSignature: runtime.setCurrentPageSignature,
      currentSignatureHit: runtime.currentSignatureHit,
      setCurrentSignatureHit: runtime.setCurrentSignatureHit,
      recentWorkbenchJump: runtime.recentWorkbenchJump,
      setRecentWorkbenchJump: runtime.setRecentWorkbenchJump,
      domainLoadSource: runtime.domainLoadSource,
      setDomainLoadSource: runtime.setDomainLoadSource,
      perfMetrics: runtime.perfMetrics,
      setPerfMetrics: runtime.setPerfMetrics,
      lastPerfSnapshotAt: runtime.lastPerfSnapshotAt,
      setLastPerfSnapshotAt: runtime.setLastPerfSnapshotAt,
    },
  }
}
