export function buildRuntimeDomainActionsState(runtime) {
  return {
    setLeadImportJob: runtime.setLeadImportJob,
    setLeadImportFailedRows: runtime.setLeadImportFailedRows,
    setLeadImportStatusFilter: runtime.setLeadImportStatusFilter,
    setLeadImportPage: runtime.setLeadImportPage,
    setLeadImportSize: runtime.setLeadImportSize,
    setLeadImportExportStatusFilter: runtime.setLeadImportExportStatusFilter,
    setLeadImportExportPage: runtime.setLeadImportExportPage,
    setLeadImportExportSize: runtime.setLeadImportExportSize,
    setError: runtime.setError,
    assignmentRuleForm: runtime.assignmentRuleForm,
    setAssignmentRuleForm: runtime.setAssignmentRuleForm,
    automationRuleForm: runtime.automationRuleForm,
    setAutomationRuleForm: runtime.setAutomationRuleForm,
    permissionRole: runtime.permissionRole,
    pendingPack: runtime.pendingPack,
    setPendingPack: runtime.setPendingPack,
    setPermissionPreview: runtime.setPermissionPreview,
    setPermissionMatrix: runtime.setPermissionMatrix,
    setAdminUsers: runtime.setAdminUsers,
    setInviteResult: runtime.setInviteResult,
    setInviteForm: runtime.setInviteForm,
    inviteForm: runtime.inviteForm,
    approvalTemplateForm: runtime.approvalTemplateForm,
    setApprovalTemplateForm: runtime.setApprovalTemplateForm,
    setApprovalTemplates: runtime.setApprovalTemplates,
    approvalInstanceForm: runtime.approvalInstanceForm,
    setApprovalInstanceForm: runtime.setApprovalInstanceForm,
    approvalActionComment: runtime.approvalActionComment,
    setApprovalActionComment: runtime.setApprovalActionComment,
    approvalTransferTo: runtime.approvalTransferTo,
    setApprovalTransferTo: runtime.setApprovalTransferTo,
    setApprovalActionResult: runtime.setApprovalActionResult,
    approvalPendingTaskIds: runtime.approvalPendingTaskIds,
    setApprovalPendingTaskIds: runtime.setApprovalPendingTaskIds,
    approvalDetail: runtime.approvalDetail,
    setSelectedNotificationJobs: runtime.setSelectedNotificationJobs,
    notificationJobs: runtime.notificationJobs,
    selectedNotificationJobs: runtime.selectedNotificationJobs,
    notificationStatusFilter: runtime.notificationStatusFilter,
    notificationPage: runtime.notificationPage,
    notificationSize: runtime.notificationSize,
    tenantForm: runtime.tenantForm,
    setTenantForm: runtime.setTenantForm,
    setLastCreatedTenant: runtime.setLastCreatedTenant,
    setTenantRows: runtime.setTenantRows,
    setAuditRangeError: runtime.setAuditRangeError,
    auditUser: runtime.auditUser,
    auditRole: runtime.auditRole,
    auditAction: runtime.auditAction,
    auditFrom: runtime.auditFrom,
    auditTo: runtime.auditTo,
    reportOwner: runtime.reportOwner,
    reportDepartment: runtime.reportDepartment,
    reportTimezone: runtime.reportTimezone,
    reportCurrency: runtime.reportCurrency,
    reportDesignerForm: runtime.reportDesignerForm,
    setReportDesignerForm: runtime.setReportDesignerForm,
    setDesignerRunResult: runtime.setDesignerRunResult,
  }
}

export function buildRuntimeDomainActionsLoaders(loaders) {
  return {
    loadLeadAssignmentRules: loaders.loadLeadAssignmentRules,
    loadAutomationRulesV1: loaders.loadAutomationRulesV1,
    loadPermissionConflicts: loaders.loadPermissionConflicts,
    loadAdminUsers: loaders.loadAdminUsers,
    loadApprovalTemplates: loaders.loadApprovalTemplates,
    loadApprovalStats: loaders.loadApprovalStats,
    loadApprovalInstances: loaders.loadApprovalInstances,
    loadApprovalTasks: loaders.loadApprovalTasks,
    loadApprovalDetail: loaders.loadApprovalDetail,
    loadNotificationJobs: loaders.loadNotificationJobs,
    loadTenants: loaders.loadTenants,
    loadApprovalTemplateVersions: loaders.loadApprovalTemplateVersions,
    hasInvalidAuditRange: loaders.hasInvalidAuditRange,
  }
}

export function buildRuntimeShellPrefetchBindings(params) {
  return {
    authToken: params.auth?.token,
    pageSignature: params.pageSignature,
    customerQ: params.customerQ,
    customerStatus: params.customerStatus,
    customerSize: params.customerSize,
    canSkipFetch: params.canSkipFetch,
    loadCustomers: params.loadCustomers,
    markFetched: params.markFetched,
    loadApprovalTemplates: params.loadApprovalTemplates,
    loadApprovalStats: params.loadApprovalStats,
    loadLeads: params.loadLeads,
    leadQ: params.leadQ,
    leadStatus: params.leadStatus,
    leadSize: params.leadSize,
    loadOpportunities: params.loadOpportunities,
    loadTasks: params.loadTasks,
    loadWorkbenchToday: params.loadWorkbenchToday,
    loadReports: params.loadReports,
    markChunkPreloadHit: params.markChunkPreloadHit,
    markNavStart: params.markNavStart,
    activePage: params.activePage,
    loadReasonRef: params.loadReasonRef,
    setActivePage: params.setActivePage,
    navigate: params.navigate,
    pageToPath: params.pageToPath,
    pageChunkPreloaders: params.pageChunkPreloaders,
    pageDomainPreloaders: params.pageDomainPreloaders,
    prefetchI18nNamespaces: params.prefetchI18nNamespaces,
  }
}

export function buildRuntimeShellWorkbenchBindings(params) {
  return {
    activePage: params.activePage,
    setActivePage: params.setActivePage,
    navigate: params.navigate,
    pageToPath: params.pageToPath,
    markNavStart: params.markNavStart,
    markWorkbenchJumpDecision: params.markWorkbenchJumpDecision,
    markWorkbenchActionResult: params.markWorkbenchActionResult,
    loadReasonRef: params.loadReasonRef,
    setPaymentStatus: params.setPaymentStatus,
    setContractStatus: params.setContractStatus,
    setApprovalTaskStatus: params.setApprovalTaskStatus,
    setFollowCustomerId: params.setFollowCustomerId,
    setFollowQ: params.setFollowQ,
    setFollowUpForm: params.setFollowUpForm,
    setQuoteOpportunityFilter: params.setQuoteOpportunityFilter,
    setQuoteStatusFilter: params.commerceDomain.quotes.setStatusFilter,
    setQuoteOwnerFilter: params.commerceDomain.quotes.setOwnerFilter,
    setQuotePrefill: params.runtime.setQuotePrefill,
    setOrderOpportunityFilter: params.setOrderOpportunityFilter,
    setOrderStatusFilter: params.commerceDomain.orders.setStatusFilter,
    setOrderOwnerFilter: params.commerceDomain.orders.setOwnerFilter,
    setLeadQ: params.runtime.setLeadQ,
    setLeadStatus: params.runtime.setLeadStatus,
    setLeadPage: params.runtime.setLeadPage,
    setLeadSize: params.runtime.setLeadSize,
    leadSize: params.leadSize,
    setCustomerQ: params.runtime.setCustomerQ,
    setCustomerStatus: params.runtime.setCustomerStatus,
    setCustomerPage: params.runtime.setCustomerPage,
    setCustomerSize: params.runtime.setCustomerSize,
    customerSize: params.customerSize,
    workbenchJumpRef: params.workbenchJumpRef,
    onWorkbenchJumpMeta: params.markWorkbenchJumpMeta,
  }
}

export function buildRuntimeShellPerfBindings(params) {
  return {
    activePage: params.activePage,
    markNavEnd: params.markNavEnd,
    markRenderCommit: params.markRenderCommit,
    markFirstInteractive: params.markFirstInteractive,
    devEnabled: typeof import.meta !== 'undefined' && !!import.meta.env?.DEV,
    getMetrics: params.getMetrics,
    setPerfMetrics: params.runtime.setPerfMetrics,
    currentLoaderKey: params.runtime.currentLoaderKey,
    lastRefreshReason: params.runtime.lastRefreshReason,
    currentPageSignature: params.runtime.currentPageSignature,
    domainLoadSource: params.runtime.domainLoadSource,
    setLastPerfSnapshotAt: params.runtime.setLastPerfSnapshotAt,
  }
}
