import { useCallback, useMemo } from 'react'
import { buildRuntimeCommonPageLoaders } from './buildRuntimeCommonPageLoaders'
import { buildRuntimeKeyPageLoaders } from './buildRuntimeKeyPageLoaders'

export function useRuntimePageLoaders({
  leadQ,
  leadStatus,
  leadImportStatusFilter,
  leadImportPage,
  leadImportSize,
  leadImportExportStatusFilter,
  leadImportExportPage,
  leadImportExportSize,
  leadImportJobId,
  leadPage,
  leadSize,
  loadLeads,
  loadLeadImportJobs,
  loadLeadImportFailedRows,
  loadLeadImportExportJobs,
  loadLeadImportMetrics,
  canViewOpsMetrics,
  customerQ,
  customerStatus,
  customerPage,
  customerSize,
  loadCustomers,
  oppStage,
  opportunityPage,
  opportunitySize,
  loadOpportunities,
  contactQ,
  contactPage,
  contactSize,
  loadContacts,
  contractQ,
  contractStatus,
  contractPage,
  contractSize,
  loadContracts,
  paymentStatus,
  paymentPage,
  paymentSize,
  loadPayments,
  commerceDomain,
  quoteOpportunityFilter,
  orderOpportunityFilter,
  followCustomerId,
  followQ,
  loadFollowUps,
  loadTasks,
  auditFrom,
  auditTo,
  reportOwner,
  reportDepartment,
  reportTimezone,
  auditRole,
  reportCurrency,
  canViewReports,
  reportExportStatusFilter,
  reportExportJobsPage,
  reportExportJobsSize,
  loadWorkbenchToday,
  loadReports,
  loadReportExportJobs,
  canViewAudit,
  auditUser,
  auditAction,
  exportStatusFilter,
  exportJobsPage,
  exportJobsSize,
  loadAudit,
  loadExportJobs,
  loadPermissionMatrix,
  loadPermissionConflicts,
  canManageUsers,
  loadAdminUsers,
  loadTenants,
  canManageSalesAutomation,
  loadLeadAssignmentRules,
  loadAutomationRulesV1,
  approvalTaskStatus,
  approvalOverdueOnly,
  approvalEscalatedOnly,
  notificationStatusFilter,
  notificationPage,
  notificationSize,
  loadApprovalTemplates,
  loadApprovalStats,
  loadApprovalInstances,
  loadApprovalTasks,
  loadNotificationJobs,
  loadDesignerTemplates,
}) {
  const pageSignature = useCallback((pageKey, filters, pageNo, pageSize) => {
    return JSON.stringify({
      pageKey,
      filters,
      pageNo: Number(pageNo || 1),
      pageSize: Number(pageSize || 0),
    })
  }, [])

  const commonPageLoaders = useMemo(
    () =>
      buildRuntimeCommonPageLoaders({
        pageSignature,
        leadQ,
        leadStatus,
        leadImportStatusFilter,
        leadImportPage,
        leadImportSize,
        leadImportExportStatusFilter,
        leadImportExportPage,
        leadImportExportSize,
        leadImportJobId,
        leadPage,
        leadSize,
        loadLeads,
        loadLeadImportJobs,
        loadLeadImportFailedRows,
        loadLeadImportExportJobs,
        loadLeadImportMetrics,
        canViewOpsMetrics,
        customerQ,
        customerStatus,
        customerPage,
        customerSize,
        loadCustomers,
        oppStage,
        opportunityPage,
        opportunitySize,
        loadOpportunities,
        contactQ,
        contactPage,
        contactSize,
        loadContacts,
        contractQ,
        contractStatus,
        contractPage,
        contractSize,
        loadContracts,
        paymentStatus,
        paymentPage,
        paymentSize,
        loadPayments,
        commerceDomain,
        quoteOpportunityFilter,
        orderOpportunityFilter,
        followCustomerId,
        followQ,
        loadFollowUps,
        loadTasks,
      }),
    [
      pageSignature,
      leadQ, leadStatus, leadImportStatusFilter, leadImportPage, leadImportSize,
      leadImportExportStatusFilter, leadImportExportPage, leadImportExportSize,
      leadImportJobId, leadPage, leadSize, canViewOpsMetrics,
      customerQ, customerStatus, customerPage, customerSize,
      oppStage, opportunityPage, opportunitySize,
      contactQ, contactPage, contactSize,
      contractQ, contractStatus, contractPage, contractSize,
      paymentStatus, paymentPage, paymentSize,
      commerceDomain,
      quoteOpportunityFilter, orderOpportunityFilter,
      followCustomerId, followQ,
      loadLeads, loadLeadImportJobs, loadLeadImportFailedRows, loadLeadImportExportJobs,
      loadLeadImportMetrics, loadCustomers, loadOpportunities, loadContacts,
      loadContracts, loadPayments, loadFollowUps, loadTasks,
    ],
  )

  const keyPageLoaders = useMemo(
    () =>
      buildRuntimeKeyPageLoaders({
        pageSignature,
        auditFrom,
        auditTo,
        reportOwner,
        reportDepartment,
        reportTimezone,
        auditRole,
        reportCurrency,
        canViewReports,
        reportExportStatusFilter,
        reportExportJobsPage,
        reportExportJobsSize,
        loadTasks,
        loadWorkbenchToday,
        loadReports,
        loadReportExportJobs,
        auditUser,
        auditAction,
        exportStatusFilter,
        exportJobsPage,
        exportJobsSize,
        canViewAudit,
        loadAudit,
        loadExportJobs,
        loadPermissionMatrix,
        loadPermissionConflicts,
        canManageUsers,
        loadAdminUsers,
        loadTenants,
        canManageSalesAutomation,
        loadLeadAssignmentRules,
        loadAutomationRulesV1,
        approvalTaskStatus,
        approvalOverdueOnly,
        approvalEscalatedOnly,
        notificationStatusFilter,
        notificationPage,
        notificationSize,
        loadApprovalTemplates,
        loadApprovalStats,
        loadApprovalInstances,
        loadApprovalTasks,
        loadNotificationJobs,
        loadDesignerTemplates,
      }),
    [
      pageSignature,
      auditFrom, auditTo, reportOwner, reportDepartment, reportTimezone,
      auditRole, reportCurrency, canViewReports, reportExportStatusFilter,
      reportExportJobsPage, reportExportJobsSize,
      auditUser, auditAction, exportStatusFilter, exportJobsPage, exportJobsSize,
      canViewAudit, canManageUsers, canManageSalesAutomation,
      approvalTaskStatus, approvalOverdueOnly, approvalEscalatedOnly,
      notificationStatusFilter, notificationPage, notificationSize,
      loadTasks, loadWorkbenchToday, loadReports, loadReportExportJobs,
      loadAudit, loadExportJobs, loadPermissionMatrix, loadPermissionConflicts,
      loadAdminUsers, loadTenants, loadLeadAssignmentRules, loadAutomationRulesV1,
      loadApprovalTemplates, loadApprovalStats, loadApprovalInstances, loadApprovalTasks,
      loadNotificationJobs, loadDesignerTemplates,
    ],
  )

  return { pageSignature, commonPageLoaders, keyPageLoaders }
}
