ALTER TABLE tenants
  ADD COLUMN IF NOT EXISTS market_profile VARCHAR(16) NOT NULL DEFAULT 'CN',
  ADD COLUMN IF NOT EXISTS tax_rule VARCHAR(32) NOT NULL DEFAULT 'VAT_CN',
  ADD COLUMN IF NOT EXISTS approval_mode VARCHAR(32) NOT NULL DEFAULT 'STRICT',
  ADD COLUMN IF NOT EXISTS channels_json VARCHAR(400) NOT NULL DEFAULT '["WECOM","DINGTALK"]',
  ADD COLUMN IF NOT EXISTS data_residency VARCHAR(40) NOT NULL DEFAULT 'CN',
  ADD COLUMN IF NOT EXISTS mask_level VARCHAR(32) NOT NULL DEFAULT 'STANDARD';

ALTER TABLE opportunities
  ADD COLUMN IF NOT EXISTS settlement_currency VARCHAR(16) NOT NULL DEFAULT 'CNY',
  ADD COLUMN IF NOT EXISTS exchange_rate_snapshot VARCHAR(40) NOT NULL DEFAULT '1.000000@SYSTEM',
  ADD COLUMN IF NOT EXISTS tax_display_mode VARCHAR(24) NOT NULL DEFAULT 'TAX_INCLUSIVE',
  ADD COLUMN IF NOT EXISTS compliance_tag VARCHAR(32) NOT NULL DEFAULT 'STANDARD';

ALTER TABLE quotes
  ADD COLUMN IF NOT EXISTS settlement_currency VARCHAR(16) NOT NULL DEFAULT 'CNY',
  ADD COLUMN IF NOT EXISTS exchange_rate_snapshot VARCHAR(40) NOT NULL DEFAULT '1.000000@SYSTEM',
  ADD COLUMN IF NOT EXISTS invoice_status VARCHAR(24) NOT NULL DEFAULT 'NOT_REQUIRED',
  ADD COLUMN IF NOT EXISTS tax_display_mode VARCHAR(24) NOT NULL DEFAULT 'TAX_INCLUSIVE',
  ADD COLUMN IF NOT EXISTS compliance_tag VARCHAR(32) NOT NULL DEFAULT 'STANDARD';

ALTER TABLE order_records
  ADD COLUMN IF NOT EXISTS settlement_currency VARCHAR(16) NOT NULL DEFAULT 'CNY',
  ADD COLUMN IF NOT EXISTS exchange_rate_snapshot VARCHAR(40) NOT NULL DEFAULT '1.000000@SYSTEM',
  ADD COLUMN IF NOT EXISTS invoice_status VARCHAR(24) NOT NULL DEFAULT 'NOT_REQUIRED',
  ADD COLUMN IF NOT EXISTS tax_display_mode VARCHAR(24) NOT NULL DEFAULT 'TAX_INCLUSIVE',
  ADD COLUMN IF NOT EXISTS compliance_tag VARCHAR(32) NOT NULL DEFAULT 'STANDARD';

ALTER TABLE contracts
  ADD COLUMN IF NOT EXISTS settlement_currency VARCHAR(16) NOT NULL DEFAULT 'CNY',
  ADD COLUMN IF NOT EXISTS exchange_rate_snapshot VARCHAR(40) NOT NULL DEFAULT '1.000000@SYSTEM',
  ADD COLUMN IF NOT EXISTS invoice_status VARCHAR(24) NOT NULL DEFAULT 'NOT_REQUIRED',
  ADD COLUMN IF NOT EXISTS tax_display_mode VARCHAR(24) NOT NULL DEFAULT 'TAX_INCLUSIVE',
  ADD COLUMN IF NOT EXISTS compliance_tag VARCHAR(32) NOT NULL DEFAULT 'STANDARD';

ALTER TABLE payments
  ADD COLUMN IF NOT EXISTS settlement_currency VARCHAR(16) NOT NULL DEFAULT 'CNY',
  ADD COLUMN IF NOT EXISTS exchange_rate_snapshot VARCHAR(40) NOT NULL DEFAULT '1.000000@SYSTEM',
  ADD COLUMN IF NOT EXISTS invoice_status VARCHAR(24) NOT NULL DEFAULT 'NOT_REQUIRED',
  ADD COLUMN IF NOT EXISTS tax_display_mode VARCHAR(24) NOT NULL DEFAULT 'TAX_INCLUSIVE',
  ADD COLUMN IF NOT EXISTS compliance_tag VARCHAR(32) NOT NULL DEFAULT 'STANDARD';

UPDATE tenants
SET market_profile = COALESCE(NULLIF(TRIM(market_profile), ''), 'CN'),
    tax_rule = COALESCE(NULLIF(TRIM(tax_rule), ''), 'VAT_CN'),
    approval_mode = COALESCE(NULLIF(TRIM(approval_mode), ''), 'STRICT'),
    channels_json = COALESCE(NULLIF(TRIM(channels_json), ''), '["WECOM","DINGTALK"]'),
    data_residency = COALESCE(NULLIF(TRIM(data_residency), ''), 'CN'),
    mask_level = COALESCE(NULLIF(TRIM(mask_level), ''), 'STANDARD')
WHERE market_profile IS NULL
   OR tax_rule IS NULL
   OR approval_mode IS NULL
   OR channels_json IS NULL
   OR data_residency IS NULL
   OR mask_level IS NULL;
