import { formatMoney, formatDateTime, translateStatus, translateStage } from '../../../../shared'
import { copyIdToClipboard } from './shared'

export function buildCustomer360SectionConfigs({
  t,
  customer,
  related,
  moduleMeta,
  onNavigateTarget,
  onQuickCreateFollowUp,
  onQuickCreateQuote,
  onQuickViewOrders,
  onQuickUrgeApproval,
  onRefreshModules,
}) {
  return [
    {
      key: 'contacts',
      title: t('contacts'),
      items: related.contacts,
      buildMainText: (item) => `${item.name || '-'} (${item.title || '-'})`,
      buildStatusText: () => '-',
      buildTimeText: (item) => formatDateTime(item.updatedAt || item.createdAt),
      onOpen: (item) => onNavigateTarget && onNavigateTarget('contacts', { q: item.name || '', page: 1 }),
      onCopyId: (item) => copyIdToClipboard(item.id),
      onQuickAction: (item) =>
        onQuickCreateFollowUp && onQuickCreateFollowUp({ customerId: customer?.id, id: customer?.id, owner: customer?.owner, q: item.name || '' }),
      quickLabel: t('quickCreateFollowUp'),
      loading: moduleMeta?.contacts?.loading,
      error: moduleMeta?.contacts?.error,
      onRetry: () => onRefreshModules?.(['contacts']),
    },
    {
      key: 'opportunities',
      title: t('pipeline'),
      items: related.opportunities,
      buildMainText: (item) => item.title || `${item.owner || '-'} / ${translateStage(t, item.stage)}`,
      buildStatusText: (item) => translateStage(t, item.stage),
      buildTimeText: (item) => formatDateTime(item.updatedAt || item.createdAt),
      onOpen: (item) => onNavigateTarget && onNavigateTarget('pipeline', { q: item.owner || '', page: 1 }),
      onCopyId: (item) => copyIdToClipboard(item.id),
      onQuickAction: () => onQuickCreateQuote && onQuickCreateQuote(),
      quickLabel: t('quickCreateQuote'),
      loading: moduleMeta?.opportunities?.loading,
      error: moduleMeta?.opportunities?.error,
      onRetry: () => onRefreshModules?.(['opportunities']),
    },
    {
      key: 'quotes',
      title: t('quotes'),
      items: related.quotes,
      buildMainText: (item) => item.title || item.quoteNo || item.id,
      buildStatusText: (item) => translateStatus(t, item.status),
      buildTimeText: (item) => formatDateTime(item.updatedAt || item.createdAt),
      onOpen: (item) =>
        onNavigateTarget &&
        onNavigateTarget('quotes', {
          owner: item.owner || '',
          status: item.status || '',
          opportunityId: item.opportunityId || '',
          customerId: item.customerId || customer?.id || '',
          page: 1,
        }),
      onCopyId: (item) => copyIdToClipboard(item.id),
      onQuickAction: () => onQuickViewOrders && onQuickViewOrders(),
      quickLabel: t('quickViewOrders'),
      loading: moduleMeta?.quotes?.loading,
      error: moduleMeta?.quotes?.error,
      onRetry: () => onRefreshModules?.(['quotes']),
    },
    {
      key: 'orders',
      title: t('orders'),
      items: related.orders,
      buildMainText: (item) => item.orderNo || item.id,
      buildStatusText: (item) => translateStatus(t, item.status),
      buildTimeText: (item) => formatDateTime(item.updatedAt || item.createdAt),
      onOpen: (item) =>
        onNavigateTarget &&
        onNavigateTarget('orders', {
          owner: item.owner || '',
          status: item.status || '',
          opportunityId: item.opportunityId || '',
          customerId: item.customerId || customer?.id || '',
          page: 1,
        }),
      onCopyId: (item) => copyIdToClipboard(item.id),
      onQuickAction: () => onQuickViewOrders && onQuickViewOrders(),
      quickLabel: t('quickViewOrders'),
      loading: moduleMeta?.orders?.loading,
      error: moduleMeta?.orders?.error,
      onRetry: () => onRefreshModules?.(['orders']),
    },
    {
      key: 'contracts',
      title: t('contracts'),
      items: related.contracts,
      buildMainText: (item) => item.contractNo || item.title || item.id,
      buildStatusText: (item) => translateStatus(t, item.status),
      buildTimeText: (item) => formatDateTime(item.signDate || item.updatedAt || item.createdAt),
      onOpen: (item) => onNavigateTarget && onNavigateTarget('contracts', { status: item.status || '', q: item.contractNo || '', page: 1 }),
      onCopyId: (item) => copyIdToClipboard(item.id),
      onQuickAction: () => onQuickUrgeApproval && onQuickUrgeApproval(),
      quickLabel: t('quickUrgeApproval'),
      loading: moduleMeta?.contracts?.loading,
      error: moduleMeta?.contracts?.error,
      onRetry: () => onRefreshModules?.(['contracts']),
    },
    {
      key: 'payments',
      title: t('payments'),
      items: related.payments,
      buildMainText: (item) => formatMoney(item.amount),
      buildStatusText: (item) => translateStatus(t, item.status),
      buildTimeText: (item) => formatDateTime(item.receivedDate || item.updatedAt || item.createdAt),
      onOpen: (item) => onNavigateTarget && onNavigateTarget('payments', { status: item.status || '', page: 1 }),
      onCopyId: (item) => copyIdToClipboard(item.id),
      loading: moduleMeta?.payments?.loading,
      error: moduleMeta?.payments?.error,
      onRetry: () => onRefreshModules?.(['payments']),
    },
    {
      key: 'approvals',
      title: t('approvals'),
      items: related.approvals,
      buildMainText: (item) => `${item.bizType || '-'} #${item.bizId || '-'} `,
      buildStatusText: (item) => translateStatus(t, item.status),
      buildTimeText: (item) => formatDateTime(item.createdAt),
      onOpen: (item) => onNavigateTarget && onNavigateTarget('approvals', { status: item.status || 'PENDING', page: 1 }),
      onCopyId: (item) => copyIdToClipboard(item.id),
      onQuickAction: () => onQuickUrgeApproval && onQuickUrgeApproval(),
      quickLabel: t('quickUrgeApproval'),
      loading: moduleMeta?.approvals?.loading,
      error: moduleMeta?.approvals?.error,
      onRetry: () => onRefreshModules?.(['approvals']),
    },
    {
      key: 'audits',
      title: t('audit'),
      items: related.audits,
      buildMainText: (item) => item.action || '-',
      buildStatusText: () => '-',
      buildTimeText: (item) => formatDateTime(item.createdAt),
      onOpen: (item) => onNavigateTarget && onNavigateTarget('audit', { q: String(item.entityId || customer?.id || ''), page: 1 }),
      onCopyId: (item) => copyIdToClipboard(item.id),
      loading: moduleMeta?.audits?.loading,
      error: moduleMeta?.audits?.error,
      onRetry: () => onRefreshModules?.(['audits']),
    },
    {
      key: 'notifications',
      title: t('notifications'),
      items: related.notifications,
      buildMainText: (item) => item.eventType || item.targetType || '-',
      buildStatusText: (item) => translateStatus(t, item.status),
      buildTimeText: (item) => formatDateTime(item.createdAt),
      onOpen: () => onNavigateTarget && onNavigateTarget('approvals', { status: 'PENDING', page: 1 }),
      onCopyId: (item) => copyIdToClipboard(item.id),
      loading: moduleMeta?.notifications?.loading,
      error: moduleMeta?.notifications?.error,
      onRetry: () => onRefreshModules?.(['notifications']),
    },
  ]
}
