import { useMemo } from 'react'

export function useAppDomainBindings(input) {
  return useMemo(() => {
    // Prefer structured bindings path from useAppRootBindings/useAppMainContentInputs.
    // Fallback mapping is kept only for backward compatibility.
    if (input?.base && input?.domains && input?.actions && input?.pageActions && input?.capabilities) return input

    return {
      base: {
        currentPageLabel: input.currentPageLabel,
        lang: input.lang,
        setLang: input.setLang,
        refreshPage: input.refreshPage,
        t: input.t,
        canWrite: input.canWrite,
        role: input.role,
        error: input.error,
        loading: input.loading,
        activePage: input.activePage,
        stats: input.stats,
        reports: input.reports,
        workbenchToday: input.workbenchToday,
        canViewReports: input.canViewReports,
        auditFrom: input.auditFrom,
        auditTo: input.auditTo,
        auditRole: input.auditRole,
        reportOwner: input.reportOwner,
        setReportOwner: input.setReportOwner,
        reportDepartment: input.reportDepartment,
        setReportDepartment: input.setReportDepartment,
        reportTimezone: input.reportTimezone,
        setReportTimezone: input.setReportTimezone,
        reportCurrency: input.reportCurrency,
        setReportCurrency: input.setReportCurrency,
        reportExportJobs: input.reportExportJobs,
        reportExportStatusFilter: input.reportExportStatusFilter,
        setReportExportStatusFilter: input.setReportExportStatusFilter,
        reportExportJobsPage: input.reportExportJobsPage,
        setReportExportJobsPage: input.setReportExportJobsPage,
        reportExportJobsTotalPages: input.reportExportJobsTotalPages,
        reportExportJobsSize: input.reportExportJobsSize,
        setReportExportJobsSize: input.setReportExportJobsSize,
        autoRefreshReportJobs: input.autoRefreshReportJobs,
        setAutoRefreshReportJobs: input.setAutoRefreshReportJobs,
        quoteOpportunityFilter: input.quoteOpportunityFilter,
        orderOpportunityFilter: input.orderOpportunityFilter,
        quotePrefill: input.quotePrefill,
        consumeQuotePrefill: input.consumeQuotePrefill,
        auth: input.auth,
        tasks: input.tasks,
        reportDesignerForm: input.reportDesignerForm,
        setReportDesignerForm: input.setReportDesignerForm,
        designerTemplates: input.designerTemplates,
        designerRunResult: input.designerRunResult,
      },
      domains: {
        customer: input.customerDomain,
        commerce: input.commerceDomainBinding,
        governance: input.governanceDomain,
        approval: input.approvalDomain,
        reporting: input.reportingDomain,
        workbench: input.workbenchDomain || {},
      },
      actions: {
        exportReportCsv: input.exportReportCsv,
        loadReportExportJobs: input.loadReportExportJobs,
        retryReportExportJob: input.retryReportExportJob,
        downloadReportExportJob: input.downloadReportExportJob,
        performLogout: input.performLogout,
        navigateToWorkbenchTarget: input.navigateToWorkbenchTarget,
        createTaskShortcut: input.createTaskShortcut,
        trackWorkbenchEvent: input.trackWorkbenchEvent,
        toggleTaskDone: input.toggleTaskDone,
        createReportDesignerTemplate: input.createReportDesignerTemplate,
        updateReportDesignerTemplate: input.updateReportDesignerTemplate,
        runReportDesignerTemplate: input.runReportDesignerTemplate,
        loadDesignerTemplates: input.loadDesignerTemplates,
      },
      pageActions: {
        saveLeadAssignmentRule: input.saveLeadAssignmentRule,
        saveAutomationRule: input.saveAutomationRule,
        changePermission: input.changePermission,
        previewPermissionPack: input.previewPermissionPack,
        commitPendingPack: input.commitPendingPack,
        rollbackPermissionRole: input.rollbackPermissionRole,
        saveAdminUser: input.saveAdminUser,
        unlockAdminUser: input.unlockAdminUser,
        getAdminUserError: input.getAdminUserError,
        inviteUser: input.inviteUser,
        createApprovalTemplate: input.createApprovalTemplate,
        submitApprovalInstance: input.submitApprovalInstance,
        updateApprovalTemplate: input.updateApprovalTemplate,
        actApprovalTask: input.actApprovalTask,
        urgeApprovalTask: input.urgeApprovalTask,
        publishApprovalTemplate: input.publishApprovalTemplate,
        rollbackApprovalTemplate: input.rollbackApprovalTemplate,
        retryNotificationJob: input.retryNotificationJob,
        toggleNotificationJob: input.toggleNotificationJob,
        toggleAllNotificationJobs: input.toggleAllNotificationJobs,
        retryNotificationJobsByIds: input.retryNotificationJobsByIds,
        retryNotificationJobsByFilter: input.retryNotificationJobsByFilter,
        createTenant: input.createTenant,
        updateTenant: input.updateTenant,
      },
      crudActions: input.crudActions || {},
      capabilities: {
        canViewReports: input.canViewReports,
        canManagePermissions: input.canManagePermissions,
        canManageUsers: input.canManageUsers,
        canManageSalesAutomation: input.canManageSalesAutomation,
        canViewAudit: input.canViewAudit,
      },
    }
  }, [input])
}
