/* eslint-disable no-unused-vars */
import { lazy, Suspense, useCallback, useEffect, useMemo } from 'react'
import { API_BASE, api } from '../../shared'
import { AppProviders } from '../../context/AppProviders'
import { ensureI18nNamespaces, getI18nNamespacesForPage, tFactory } from '../../i18n'
import { useAppNavigationModel } from '../useAppNavigationModel'
import { useCoreListDomainLoaders } from '../useCoreListDomainLoaders'
import { useGovernanceDomainLoaders } from '../useGovernanceDomainLoaders'
import { useApprovalDomainLoaders } from '../useApprovalDomainLoaders'
import { useReportingAuditDomainLoaders } from '../useReportingAuditDomainLoaders'
import { useWorkbenchDomainLoaders } from '../useWorkbenchDomainLoaders'
import { useCommerceDomainLoaders } from '../useCommerceDomainLoaders'
import { useLeadImportDomainLoaders } from '../useLeadImportDomainLoaders'
import { useAppAuthModel } from '../useAppAuthModel'
import { useAppStateModel } from '../useAppStateModel'
import { PAGE_CHUNK_PRELOADERS, PAGE_DOMAIN_PRELOADERS, PAGE_TO_PATH, PATH_TO_PAGE, normalizeDateFormat } from './runtime/routeConfig'
import { useRuntimeRouting } from './runtime/useRuntimeRouting'
import { useRuntimeLoaders } from './runtime/useRuntimeLoaders'
import { useRuntimeAuthBranch } from './runtime/useRuntimeAuthBranch.jsx'
import { useRuntimePersistenceEffects } from './runtime/useRuntimePersistenceEffects'
import { useRuntimePageLoaders } from './runtime/useRuntimePageLoaders'
import { useRuntimeDomainActions } from './runtime/useRuntimeDomainActions'
import { useRuntimePageModelSync } from './runtime/useRuntimePageModelSync'
import { buildRuntimePageModelContext } from './runtime/useRuntimePageModelContext'
import { useRuntimeFormValidators } from './runtime/useRuntimeFormValidators'
import { useRuntimeAuthActions } from './runtime/useRuntimeAuthActions'
import { useRuntimeCrudDomainActions } from './runtime/useRuntimeCrudDomainActions'
import { useRuntimeStateSlices } from './runtime/useRuntimeStateSlices'
import { buildRuntimeDomainActionsConfig } from './runtime/buildRuntimeDomainActionsConfig'
import { useRuntimeKernelState } from './runtime-kernel/useRuntimeKernelState'
import '../../../App.css'

const AuthShell = lazy(() => import('../../components/shell/AuthShell'))
const AppShell = lazy(() => import('../../components/shell/AppShell'))


function AppRuntimeEngine() {
  const {
    lang,
    setLang,
    auth,
    setAuth,
    persisted,
    readPageSize,
  } = useAppStateModel()
  const runtime = useRuntimeStateSlices({ persisted, readPageSize }).runtime
  const {
    location,
    navigate,
    perfEnabledByQuery,
    apiContext,
    isAuthRoute,
  } = useRuntimeRouting({ auth, lang })
  const t = useMemo(() => tFactory(lang), [lang])
  const {
    loading,
    error,
    setError,
    loginError,
    setLoginError,
    crudErrors,
    setCrudErrors,
    crudFieldErrors,
    setCrudFieldErrors,
    stats,
    leads,
    setLeads,
    customers,
    setCustomers,
    tasks,
    setTasks,
    opportunities,
    setOpportunities,
    followUps,
    setFollowUps,
    contacts,
    setContacts,
    contracts,
    setContracts,
    payments,
    setPayments,
    auditLogs,
    setAuditLogs,
    reports,
    setReports,
    workbenchToday,
    setWorkbenchToday,
    customerTimeline,
    setCustomerTimeline,
    opportunityTimeline,
    setOpportunityTimeline,
    permissionMatrix,
    setPermissionMatrix,
    permissionConflicts,
    setPermissionConflicts,
    permissionRole,
    setPermissionRole,
    permissionPreview,
    setPermissionPreview,
    pendingPack,
    setPendingPack,
    exportJobs,
    setExportJobs,
    exportJobsPage,
    setExportJobsPage,
    exportJobsTotalPages,
    setExportJobsTotalPages,
    exportJobsSize,
    setExportJobsSize,
    autoRefreshJobs,
    setAutoRefreshJobs,
    exportStatusFilter,
    setExportStatusFilter,
    reportExportJobs,
    setReportExportJobs,
    reportExportJobsPage,
    setReportExportJobsPage,
    reportExportJobsTotalPages,
    setReportExportJobsTotalPages,
    reportExportJobsSize,
    setReportExportJobsSize,
    designerTemplates,
    setDesignerTemplates,
    designerRunResult,
    setDesignerRunResult,
    leadImportJob,
    setLeadImportJob,
    leadImportJobs,
    setLeadImportJobs,
    leadImportStatusFilter,
    setLeadImportStatusFilter,
    leadImportPage,
    setLeadImportPage,
    leadImportTotalPages,
    setLeadImportTotalPages,
    leadImportSize,
    setLeadImportSize,
    leadImportFailedRows,
    setLeadImportFailedRows,
    leadImportMetrics,
    setLeadImportMetrics,
    leadImportExportJobs,
    setLeadImportExportJobs,
    leadImportExportStatusFilter,
    setLeadImportExportStatusFilter,
    leadImportExportPage,
    setLeadImportExportPage,
    leadImportExportTotalPages,
    setLeadImportExportTotalPages,
    leadImportExportSize,
    setLeadImportExportSize,
    leadAssignmentRules,
    setLeadAssignmentRules,
    assignmentRuleForm,
    setAssignmentRuleForm,
    automationRules,
    setAutomationRules,
    automationRuleForm,
    setAutomationRuleForm,
    autoRefreshReportJobs,
    setAutoRefreshReportJobs,
    reportExportStatusFilter,
    setReportExportStatusFilter,
    customerQ,
    setCustomerQ,
    leadQ,
    setLeadQ,
    leadStatus,
    setLeadStatus,
    customerStatus,
    setCustomerStatus,
    oppStage,
    setOppStage,
    followCustomerId,
    setFollowCustomerId,
    followQ,
    setFollowQ,
    auditUser,
    setAuditUser,
    auditRole,
    setAuditRole,
    auditAction,
    setAuditAction,
    auditFrom,
    setAuditFrom,
    auditTo,
    setAuditTo,
    reportOwner,
    setReportOwner,
    reportDepartment,
    setReportDepartment,
    reportTimezone,
    setReportTimezone,
    reportCurrency,
    setReportCurrency,
    quoteOpportunityFilter,
    setQuoteOpportunityFilter,
    orderOpportunityFilter,
    setOrderOpportunityFilter,
    quotePrefill,
    setQuotePrefill,
    loginForm,
    setLoginForm,
    mfaChallengeId,
    setMfaChallengeId,
    ssoConfig,
    setSsoConfig,
    ssoForm,
    setSsoForm,
    adminUsers,
    setAdminUsers,
    oidcAuthorizing,
    setOidcAuthorizing,
    sessionBootstrapping,
    setSessionBootstrapping,
    formErrors,
    setFormErrors,
    auditRangeError,
    setAuditRangeError,
    activePage,
    setActivePage,
    customerForm,
    setCustomerForm,
    leadForm,
    setLeadForm,
    opportunityForm,
    setOpportunityForm,
    followUpForm,
    setFollowUpForm,
    contactForm,
    setContactForm,
    contractForm,
    setContractForm,
    paymentForm,
    setPaymentForm,
    approvalTemplateForm,
    setApprovalTemplateForm,
    approvalInstanceForm,
    setApprovalInstanceForm,
    approvalTemplates,
    setApprovalTemplates,
    approvalStats,
    setApprovalStats,
    approvalTasks,
    setApprovalTasks,
    approvalInstances,
    setApprovalInstances,
    approvalDetail,
    setApprovalDetail,
    approvalTemplateVersions,
    setApprovalTemplateVersions,
    approvalVersionTemplateId,
    setApprovalVersionTemplateId,
    approvalTaskStatus,
    setApprovalTaskStatus,
    approvalOverdueOnly,
    setApprovalOverdueOnly,
    approvalEscalatedOnly,
    setApprovalEscalatedOnly,
    approvalActionComment,
    setApprovalActionComment,
    approvalTransferTo,
    setApprovalTransferTo,
    approvalActionResult,
    setApprovalActionResult,
    approvalPendingTaskIds,
    setApprovalPendingTaskIds,
    notificationJobs,
    setNotificationJobs,
    notificationStatusFilter,
    setNotificationStatusFilter,
    notificationPage,
    setNotificationPage,
    notificationTotalPages,
    setNotificationTotalPages,
    notificationSize,
    setNotificationSize,
    selectedNotificationJobs,
    setSelectedNotificationJobs,
    tenantForm,
    setTenantForm,
    lastCreatedTenant,
    setLastCreatedTenant,
    tenantRows,
    setTenantRows,
    inviteForm,
    setInviteForm,
    inviteResult,
    setInviteResult,
    reportDesignerForm,
    setReportDesignerForm,
    customerPage,
    setCustomerPage,
    leadPage,
    setLeadPage,
    leadTotalPages,
    setLeadTotalPages,
    leadSize,
    setLeadSize,
    customerTotalPages,
    setCustomerTotalPages,
    customerSize,
    setCustomerSize,
    opportunityPage,
    setOpportunityPage,
    opportunityTotalPages,
    setOpportunityTotalPages,
    opportunitySize,
    setOpportunitySize,
    contactQ,
    setContactQ,
    contactPage,
    setContactPage,
    contactTotalPages,
    setContactTotalPages,
    contactSize,
    setContactSize,
    contractQ,
    setContractQ,
    contractStatus,
    setContractStatus,
    contractPage,
    setContractPage,
    contractTotalPages,
    setContractTotalPages,
    contractSize,
    setContractSize,
    paymentStatus,
    setPaymentStatus,
    paymentPage,
    setPaymentPage,
    paymentTotalPages,
    setPaymentTotalPages,
    paymentSize,
    setPaymentSize,
    perfMetrics,
    setPerfMetrics,
    lastPerfSnapshotAt,
    setLastPerfSnapshotAt,
    currentLoaderKey,
    setCurrentLoaderKey,
    lastRefreshReason,
    setLastRefreshReason,
    currentPageSignature,
    setCurrentPageSignature,
    currentSignatureHit,
    setCurrentSignatureHit,
    recentWorkbenchJump,
    setRecentWorkbenchJump,
    domainLoadSource,
    setDomainLoadSource,
  } = runtime
  useEffect(() => {
    ensureI18nNamespaces(lang, getI18nNamespacesForPage(activePage)).catch(() => {})
  }, [lang, activePage])
  const kernel = useRuntimeKernelState({
    auth,
    setRecentWorkbenchJump,
    setDomainLoadSource,
  })
  const { beginPageRequest, canSkipFetch, isInFlight, markInFlight, clearInFlight, markFetched, abortAll } = kernel.pagePolicy
  const {
    markNavStart,
    markNavEnd,
    markAbort,
    markFetchLatency,
    markRenderCommit,
    markFirstInteractive,
    markCacheDecision,
    markChunkPreloadHit,
    markDuplicateFetchBlocked,
    markWorkbenchJumpDecision,
    markWorkbenchActionResult,
    markPollingActiveInstances,
    markLoginErrorLeakBlocked,
    markLoaderFallbackUsed,
    markAuthChannelMisroute,
    markRefreshSourceAnomaly,
    markCustomer360ActionResult,
    markCustomer360ModuleRefreshLatency,
    markCustomer360JumpHit,
    markCustomer360ModuleCacheHit,
    markCustomer360PrefetchHit,
    markCustomer360PrefetchAbort,
    markCustomer360PrefetchModules,
    getMetrics,
  } = kernel.perf
  const {
    seqRef,
    logoutGuardRef,
    suppressLoginErrorUntilRef,
    loadReasonRef,
    workbenchJumpRef,
    markWorkbenchJumpMeta,
    markDomainLoadSource,
    hasAuthToken,
    role,
    canWrite,
    canDeleteCustomer,
    canDeleteOpportunity,
    canViewAudit,
    canViewReports,
    canViewOpsMetrics,
    canManagePermissions,
    canManageUsers,
    canManageSalesAutomation,
  } = kernel

  const { navGroups, currentPageLabel } = useAppNavigationModel({
    t,
    permissions: {
      canViewAudit,
      canManagePermissions,
      canManageUsers,
      canManageSalesAutomation,
    },
    activePage,
    setActivePage,
    locationPathname: location.pathname,
    authToken: auth?.token,
    navigate,
    pathToPage: PATH_TO_PAGE,
    pageToPath: PAGE_TO_PATH,
  })

  const formatValidation = (err) => { const ve = err?.validationErrors; if (!ve || typeof ve !== 'object') return err.message; const first = Object.entries(ve)[0]; return first ? `${first[0]}: ${first[1]}` : err.message }
  const formatErrorMessage = useCallback((err) => {
    const msg = err?.status === 400 ? formatValidation(err) : err?.message
    return err?.requestId ? `${msg} [${err.requestId}]` : msg
  }, [])
  const {
    saveAuth,
    handleLoginError,
    handleError,
    performLogout,
  } = useAppAuthModel({
    auth,
    setAuth,
    setError,
    setLoginError,
    setCrudErrors,
    setCrudFieldErrors,
    setCurrentLoaderKey,
    setCurrentPageSignature,
    setCurrentSignatureHit,
    setRecentWorkbenchJump,
    setDomainLoadSource,
    setLastRefreshReason,
    abortAll,
    loadReasonRef,
    workbenchJumpRef,
    navigate,
    pathname: location.pathname,
    logoutGuardRef,
    suppressLoginErrorUntilRef,
    markLoginErrorLeakBlocked,
    markAuthChannelMisroute,
    t,
    formatErrorMessage,
  })
  const {
    validateLogin,
    validateSso,
    validateContactForm,
    validateCustomerForm,
    validateContractForm,
    validatePaymentForm,
    hasInvalidAuditRange,
  } = useRuntimeFormValidators({
    t,
    auth,
    loginForm,
    ssoForm,
    contactForm,
    customerForm,
    contractForm,
    paymentForm,
    auditFrom,
    auditTo,
  })

  const {
    loaders: coreListLoaders,
    paginationActions: corePaginationActions,
  } = useCoreListDomainLoaders({
    authToken: auth?.token,
    lang,
    seqRef,
    beginPageRequest,
    handleError,
    leadQ,
    leadStatus,
    leadPage,
    leadSize,
    setLeads,
    setLeadPage,
    setLeadTotalPages,
    setLeadSize,
    customerQ,
    customerStatus,
    customerPage,
    customerSize,
    setCustomers,
    setCustomerPage,
    setCustomerTotalPages,
    setCustomerSize,
    oppStage,
    opportunityPage,
    opportunitySize,
    setOpportunities,
    setOpportunityPage,
    setOpportunityTotalPages,
    setOpportunitySize,
    contactQ,
    contactPage,
    contactSize,
    setContacts,
    setContactPage,
    setContactTotalPages,
    setContactSize,
    contractQ,
    contractStatus,
    contractPage,
    contractSize,
    setContracts,
    setContractPage,
    setContractTotalPages,
    setContractSize,
    paymentStatus,
    paymentPage,
    paymentSize,
    setPayments,
    setPaymentPage,
    setPaymentTotalPages,
    setPaymentSize,
  })
  const commerceDomain = useCommerceDomainLoaders({
    authToken: auth?.token,
    lang,
    quoteOpportunityFilter,
    orderOpportunityFilter,
  })
  const {
    loadLeadImportJobs,
    loadLeadImportFailedRows,
    loadLeadImportMetrics,
    loadLeadImportExportJobs,
  } = useLeadImportDomainLoaders({
    authToken: auth?.token,
    lang,
    canViewOpsMetrics,
    leadImportStatusFilter,
    leadImportPage,
    leadImportSize,
    leadImportJob,
    setLeadImportJobs,
    setLeadImportPage,
    setLeadImportTotalPages,
    setLeadImportJob,
    setLeadImportFailedRows,
    setLeadImportMetrics,
    leadImportExportStatusFilter,
    leadImportExportPage,
    leadImportExportSize,
    setLeadImportExportJobs,
    setLeadImportExportPage,
    setLeadImportExportTotalPages,
  })
  const {
    loadLeads,
    loadCustomers,
    loadOpportunities,
    loadContacts,
    loadContracts,
    loadPayments,
  } = coreListLoaders
  const {
    onLeadPageChange,
    onCustomerPageChange,
    onOpportunityPageChange,
    onContactPageChange,
    onContractPageChange,
    onPaymentPageChange,
    onLeadSizeChange,
    onCustomerSizeChange,
    onOpportunitySizeChange,
    onContactSizeChange,
    onContractSizeChange,
    onPaymentSizeChange,
  } = corePaginationActions
  const loadTasks = async () => { const controller = beginPageRequest('tasks'); const d = await api('/tasks/search?page=1&size=10', { signal: controller.signal }, auth.token, lang); setTasks(d.items || []) }
  const loadFollowUps = async () => { const q = new URLSearchParams({ customerId: followCustomerId, q: followQ, page: '1', size: '8' }); const controller = beginPageRequest('followUps'); const d = await api('/follow-ups/search?' + q, { signal: controller.signal }, auth.token, lang); setFollowUps(d.items || []) }
  const loadSsoConfig = async () => { try { const d = await api('/auth/sso/config', {}, null, lang); setSsoConfig(d || { enabled: false, providerName: '', mode: 'mock' }) } catch { setSsoConfig({ enabled: false, providerName: '', mode: 'mock' }) } }
  const {
    loadPermissionMatrix,
    loadPermissionConflicts,
    loadLeadAssignmentRules,
    loadAutomationRulesV1,
    loadAdminUsers,
    loadTenants,
  } = useGovernanceDomainLoaders({
    canManageUsers,
    canManageSalesAutomation,
    authToken: auth?.token,
    lang,
    setPermissionMatrix,
    setPermissionConflicts,
    setLeadAssignmentRules,
    setAutomationRules,
    setAdminUsers,
    setTenantRows,
    normalizeDateFormat,
  })
  const {
    loadApprovalTemplates,
    loadApprovalStats,
    loadApprovalTasks,
    loadApprovalInstances,
    loadApprovalDetail,
    loadApprovalTemplateVersions,
    loadNotificationJobs,
  } = useApprovalDomainLoaders({
    authToken: auth?.token,
    lang,
    approvalTaskStatus,
    approvalOverdueOnly,
    approvalEscalatedOnly,
    notificationStatusFilter,
    notificationPage,
    notificationSize,
    setApprovalTemplates,
    setApprovalStats,
    setApprovalTasks,
    setApprovalInstances,
    setApprovalDetail,
    setApprovalTemplateVersions,
    setApprovalVersionTemplateId,
    setNotificationJobs,
    setNotificationPage,
    setNotificationTotalPages,
    setSelectedNotificationJobs,
  })
  const {
    loadAudit,
    loadReports,
    loadExportJobs,
    loadReportExportJobs,
    loadDesignerTemplates,
  } = useReportingAuditDomainLoaders({
    canViewAudit,
    canViewReports,
    authToken: auth?.token,
    lang,
    auditUser,
    auditRole,
    auditAction,
    auditFrom,
    auditTo,
    reportOwner,
    reportDepartment,
    reportTimezone,
    reportCurrency,
    exportStatusFilter,
    exportJobsPage,
    exportJobsSize,
    reportExportStatusFilter,
    reportExportJobsPage,
    reportExportJobsSize,
    hasInvalidAuditRange,
    setAuditRangeError,
    t,
    setAuditLogs,
    setReports,
    setExportJobs,
    setExportJobsPage,
    setExportJobsTotalPages,
    setReportExportJobs,
    setReportExportJobsPage,
    setReportExportJobsTotalPages,
    setDesignerTemplates,
  })
  const {
    loadWorkbenchToday,
    loadCustomerTimeline,
    loadOpportunityTimeline,
  } = useWorkbenchDomainLoaders({
    authToken: auth?.token,
    lang,
    auditFrom,
    auditTo,
    reportOwner,
    reportDepartment,
    reportTimezone,
    setWorkbenchToday,
    setCustomerTimeline,
    setOpportunityTimeline,
  })

  useRuntimePersistenceEffects({
    lang,
    abortAll,
    auth,
    locationPathname: location.pathname,
    sessionBootstrapping,
    navigate,
    saveAuth,
    setSessionBootstrapping,
    loadSsoConfig,
    ssoConfig,
    setLoginError,
    t,
    setOidcAuthorizing,
    loginFormTenantId: loginForm.tenantId,
    handleLoginError,
    leadQ,
    leadStatus,
    customerQ,
    customerStatus,
    oppStage,
    followCustomerId,
    followQ,
    contactQ,
    contractQ,
    contractStatus,
    paymentStatus,
    auditUser,
    auditRole,
    auditAction,
    auditFrom,
    auditTo,
    reportOwner,
    reportDepartment,
    reportTimezone,
    reportCurrency,
    customerSize,
    leadSize,
    opportunitySize,
    contactSize,
    contractSize,
    paymentSize,
    notificationSize,
    leadImportExportSize,
  })
  const { pageSignature, commonPageLoaders, keyPageLoaders } = useRuntimePageLoaders({
    leadQ,
    leadStatus,
    leadImportStatusFilter,
    leadImportPage,
    leadImportSize,
    leadImportExportStatusFilter,
    leadImportExportPage,
    leadImportExportSize,
    leadImportJobId: leadImportJob?.id,
    leadPage,
    leadSize,
    loadLeads,
    loadLeadImportJobs,
    loadLeadImportFailedRows,
    loadLeadImportExportJobs,
    loadLeadImportMetrics,
    canViewOpsMetrics,
    customerQ,
    customerStatus,
    customerPage,
    customerSize,
    loadCustomers,
    oppStage,
    opportunityPage,
    opportunitySize,
    loadOpportunities,
    contactQ,
    contactPage,
    contactSize,
    loadContacts,
    contractQ,
    contractStatus,
    contractPage,
    contractSize,
    loadContracts,
    paymentStatus,
    paymentPage,
    paymentSize,
    loadPayments,
    commerceDomain,
    quoteOpportunityFilter,
    orderOpportunityFilter,
    followCustomerId,
    followQ,
    loadFollowUps,
    loadTasks,
    auditFrom,
    auditTo,
    reportOwner,
    reportDepartment,
    reportTimezone,
    auditRole,
    reportCurrency,
    canViewReports,
    reportExportStatusFilter,
    reportExportJobsPage,
    reportExportJobsSize,
    loadWorkbenchToday,
    loadReports,
    loadReportExportJobs,
    canViewAudit,
    auditUser,
    auditAction,
    exportStatusFilter,
    exportJobsPage,
    exportJobsSize,
    loadAudit,
    loadExportJobs,
    loadPermissionMatrix,
    loadPermissionConflicts,
    canManageUsers,
    loadAdminUsers,
    loadTenants,
    canManageSalesAutomation,
    loadLeadAssignmentRules,
    loadAutomationRulesV1,
    approvalTaskStatus,
    approvalOverdueOnly,
    approvalEscalatedOnly,
    notificationStatusFilter,
    notificationPage,
    notificationSize,
    loadApprovalTemplates,
    loadApprovalStats,
    loadApprovalInstances,
    loadApprovalTasks,
    loadNotificationJobs,
    loadDesignerTemplates,
  })
  const { refreshPage } = useRuntimeLoaders({
    authToken: auth?.token,
    activePage,
    commonPageLoaders,
    keyPageLoaders,
    loadReasonRef,
    beginPageRequest,
    canSkipFetch,
    isInFlight,
    markInFlight,
    clearInFlight,
    markCacheDecision,
    markDuplicateFetchBlocked,
    markWorkbenchJumpDecision,
    markFetched,
    markFetchLatency,
    markAbort,
    markLoaderFallbackUsed,
    handleError,
    setLastRefreshReason,
    setCurrentLoaderKey,
    setCurrentPageSignature,
    setCurrentSignatureHit,
    markDomainLoadSource,
    markRefreshSourceAnomaly,
    setError,
    setLoginError,
    locationPathname: location.pathname,
    setNotificationPage,
    notificationStatusFilter,
    notificationSize,
    setLeadImportPage,
    leadImportStatusFilter,
    leadImportSize,
    setExportJobsPage,
    exportStatusFilter,
    exportJobsSize,
    setReportExportJobsPage,
    reportExportStatusFilter,
    reportExportJobsSize,
    setLeadImportExportPage,
    leadImportExportStatusFilter,
    leadImportExportSize,
    leadImportJobId: leadImportJob?.id,
    autoRefreshJobs,
    exportJobs,
    autoRefreshReportJobs,
    reportExportJobs,
    leadImportJobs,
    leadImportExportJobs,
    markPollingActiveInstances,
  })
  const {
    toggleTaskDone,
    saveLead,
    editLead,
    convertLead,
    bulkAssignLeadsByRule,
    bulkUpdateLeadStatus,
    saveCustomer,
    editCustomer,
    removeCustomer,
    saveOpportunity,
    editOpportunity,
    removeOpportunity,
    saveFollowUp,
    editFollowUp,
    removeFollowUp,
    saveContact,
    editContact,
    removeContact,
    saveContract,
    editContract,
    removeContract,
    savePayment,
    editPayment,
    removePayment,
  } = useRuntimeCrudDomainActions({
    auth,
    lang,
    t,
    canWrite,
    canDeleteCustomer,
    canDeleteOpportunity,
    handleError,
    validateCustomerForm,
    validateContactForm,
    validateContractForm,
    validatePaymentForm,
    leadForm,
    setLeadForm,
    leads,
    customerForm,
    setCustomerForm,
    customerPage,
    setCustomerPage,
    customers,
    opportunityForm,
    setOpportunityForm,
    opportunityPage,
    setOpportunityPage,
    opportunities,
    followUpForm,
    setFollowUpForm,
    contactForm,
    setContactForm,
    contactPage,
    setContactPage,
    contacts,
    contractForm,
    setContractForm,
    contractPage,
    setContractPage,
    contracts,
    paymentForm,
    setPaymentForm,
    paymentPage,
    setPaymentPage,
    payments,
    refreshPage,
    setQuotePrefill,
    activePage,
    markNavStart,
    loadReasonRef,
    setActivePage,
    navigate,
    setQuoteOpportunityFilter,
    setCrudErrors,
    setCrudFieldErrors,
  })
  const {
    submitLogin,
    submitSsoLogin,
    startOidcLogin,
  } = useRuntimeAuthActions({
    lang,
    t,
    loginForm,
    ssoForm,
    ssoConfig,
    mfaChallengeId,
    validateLogin,
    validateSso,
    setLoginError,
    setFormErrors,
    saveAuth,
    setMfaChallengeId,
    setError,
    handleLoginError,
    setOidcAuthorizing,
    logoutGuardRef,
  })

  const {
    importLeadsCsv,
    selectLeadImportJob,
    cancelLeadImportJob,
    retryLeadImportJob,
    createLeadImportFailedRowsExportJob,
    updateLeadImportExportStatusFilter,
    onLeadImportExportPageChange,
    onLeadImportExportSizeChange,
    downloadLeadImportFailedRowsExportJob,
    updateLeadImportStatusFilter,
    onLeadImportPageChange,
    onLeadImportSizeChange,
    downloadLeadImportTemplate,
    isLeadImportActionPending,
    exportReportCsv,
    createExportJob,
    retryExportJob,
    downloadExportJob,
    retryReportExportJob,
    downloadReportExportJob,
    createReportDesignerTemplate,
    updateReportDesignerTemplate,
    runReportDesignerTemplate,
    saveLeadAssignmentRule,
    saveAutomationRule,
    changePermission,
    previewPermissionPack,
    commitPendingPack,
    rollbackPermissionRole,
    saveAdminUser,
    unlockAdminUser,
    getAdminUserError,
    inviteUser,
    createApprovalTemplate,
    submitApprovalInstance,
    updateApprovalTemplate,
    actApprovalTask,
    urgeApprovalTask,
    publishApprovalTemplate,
    rollbackApprovalTemplate,
    retryNotificationJob,
    toggleNotificationJob,
    toggleAllNotificationJobs,
    retryNotificationJobsByIds,
    retryNotificationJobsByFilter,
    createTenant,
    updateTenant,
    onPrefetch,
    onNavigate,
    trackWorkbenchEvent,
    buildWorkbenchFilterSignature,
    navigateToWorkbenchTarget,
    createQuoteFromOpportunity,
    viewOrdersFromOpportunity,
    createFollowUpShortcut,
    createTaskShortcut,
    urgeApprovalShortcut,
    copyPerfSnapshot,
    consumeQuotePrefill,
    refreshLeads,
    refreshCustomers,
    refreshPipeline,
    refreshFollowUps,
    refreshContacts,
    refreshContracts,
    refreshPayments,
  } = useRuntimeDomainActions({
    ...buildRuntimeDomainActionsConfig({
      auth,
      lang,
      role,
      t,
      canViewOpsMetrics,
      canManagePermissions,
      canViewReports,
      handleError,
      refreshPage,
      state: {
        setLeadImportJob,
        setLeadImportFailedRows,
        setLeadImportStatusFilter,
        setLeadImportPage,
        setLeadImportSize,
        setLeadImportExportStatusFilter,
        setLeadImportExportPage,
        setLeadImportExportSize,
        setError,
        assignmentRuleForm,
        setAssignmentRuleForm,
        automationRuleForm,
        setAutomationRuleForm,
        permissionRole,
        pendingPack,
        setPendingPack,
        setPermissionPreview,
        setPermissionMatrix,
        setAdminUsers,
        setInviteResult,
        setInviteForm,
        inviteForm,
        approvalTemplateForm,
        setApprovalTemplateForm,
        setApprovalTemplates,
        approvalInstanceForm,
        setApprovalInstanceForm,
        approvalActionComment,
        setApprovalActionComment,
        approvalTransferTo,
        setApprovalTransferTo,
        setApprovalActionResult,
        approvalPendingTaskIds,
        setApprovalPendingTaskIds,
        approvalDetail,
        setSelectedNotificationJobs,
        notificationJobs,
        selectedNotificationJobs,
        notificationStatusFilter,
        notificationPage,
        notificationSize,
        tenantForm,
        setTenantForm,
        setLastCreatedTenant,
        setTenantRows,
        setAuditRangeError,
        auditUser,
        auditRole,
        auditAction,
        auditFrom,
        auditTo,
        reportOwner,
        reportDepartment,
        reportTimezone,
        reportCurrency,
        reportDesignerForm,
        setReportDesignerForm,
        setDesignerRunResult,
      },
      loaders: {
        loadLeadAssignmentRules,
        loadAutomationRulesV1,
        loadPermissionConflicts,
        loadAdminUsers,
        loadApprovalTemplates,
        loadApprovalStats,
        loadApprovalInstances,
        loadApprovalTasks,
        loadApprovalDetail,
        loadNotificationJobs,
        loadTenants,
        loadApprovalTemplateVersions,
        hasInvalidAuditRange,
      },
    }),
    shellBindings: {
      prefetch: {
        authToken: auth?.token,
        pageSignature,
        customerQ,
        customerStatus,
        customerSize,
        canSkipFetch,
        loadCustomers,
        markFetched,
        loadApprovalTemplates,
        loadApprovalStats,
        loadLeads,
        leadQ,
        leadStatus,
        leadSize,
        loadOpportunities,
        loadTasks,
        loadWorkbenchToday,
        loadReports,
        markChunkPreloadHit,
        markNavStart,
        activePage,
        loadReasonRef,
        setActivePage,
        navigate,
        pageToPath: PAGE_TO_PATH,
        pageChunkPreloaders: PAGE_CHUNK_PRELOADERS,
        pageDomainPreloaders: PAGE_DOMAIN_PRELOADERS,
        prefetchI18nNamespaces: (pageKey) => ensureI18nNamespaces(lang, getI18nNamespacesForPage(pageKey)),
      },
      workbench: {
        activePage,
        setActivePage,
        navigate,
        pageToPath: PAGE_TO_PATH,
        markNavStart,
        markWorkbenchJumpDecision,
        markWorkbenchActionResult,
        loadReasonRef,
        setPaymentStatus,
        setContractStatus,
        setApprovalTaskStatus,
        setFollowCustomerId,
        setFollowQ,
        setFollowUpForm,
        setQuoteOpportunityFilter,
        setQuoteStatusFilter: commerceDomain.quotes.setStatusFilter,
        setQuoteOwnerFilter: commerceDomain.quotes.setOwnerFilter,
        setQuotePrefill,
        setOrderOpportunityFilter,
        setOrderStatusFilter: commerceDomain.orders.setStatusFilter,
        setOrderOwnerFilter: commerceDomain.orders.setOwnerFilter,
        setLeadQ,
        setLeadStatus,
        setLeadPage,
        setLeadSize,
        leadSize,
        setCustomerQ,
        setCustomerStatus,
        setCustomerPage,
        setCustomerSize,
        customerSize,
        workbenchJumpRef,
        onWorkbenchJumpMeta: markWorkbenchJumpMeta,
      },
      perf: {
        activePage,
        markNavEnd,
        markRenderCommit,
        markFirstInteractive,
        devEnabled: typeof import.meta !== 'undefined' && !!import.meta.env?.DEV,
        getMetrics,
        setPerfMetrics,
        currentLoaderKey,
        lastRefreshReason,
        currentPageSignature,
        domainLoadSource,
        setLastPerfSnapshotAt,
      },
    },
    setQuotePrefill,
    refreshPage,
  })

  const pageModelCtx = buildRuntimePageModelContext({
    runtime,
    base: {
      currentPageLabel,
      lang,
      setLang,
      refreshPage,
      t,
      canWrite,
      role,
      canViewReports,
      canViewAudit,
      canManagePermissions,
      canManageUsers,
      canManageSalesAutomation,
      canDeleteCustomer,
      canDeleteOpportunity,
      navigate,
      performLogout,
      customer360Metrics: {
        markActionResult: markCustomer360ActionResult,
        markModuleRefreshLatency: markCustomer360ModuleRefreshLatency,
        markJumpHit: markCustomer360JumpHit,
        markModuleCacheHit: markCustomer360ModuleCacheHit,
        markPrefetchHit: markCustomer360PrefetchHit,
        markPrefetchAbort: markCustomer360PrefetchAbort,
        markPrefetchModules: markCustomer360PrefetchModules,
      },
    },
    reporting: {
      hasInvalidAuditRange,
      loadAudit,
      loadExportJobs,
      loadDesignerTemplates,
      loadCustomerTimeline,
      loadOpportunityTimeline,
      loadReportExportJobs,
    },
    customer: {
      toggleTaskDone,
      saveLead,
      editLead,
      convertLead,
      bulkAssignLeadsByRule,
      bulkUpdateLeadStatus,
      saveCustomer,
      editCustomer,
      removeCustomer,
      saveOpportunity,
      editOpportunity,
      removeOpportunity,
      saveFollowUp,
      editFollowUp,
      removeFollowUp,
      saveContact,
      editContact,
      removeContact,
      saveContract,
      editContract,
      removeContract,
      savePayment,
      editPayment,
      removePayment,
      onLeadPageChange,
      onCustomerPageChange,
      onOpportunityPageChange,
      onContactPageChange,
      onContractPageChange,
      onPaymentPageChange,
      onLeadSizeChange,
      onCustomerSizeChange,
      onOpportunitySizeChange,
      onContactSizeChange,
      onContractSizeChange,
      onPaymentSizeChange,
    },
    commerce: { commerceDomain },
    governance: {
      importLeadsCsv,
      updateLeadImportStatusFilter,
      onLeadImportPageChange,
      onLeadImportSizeChange,
      selectLeadImportJob,
      cancelLeadImportJob,
      retryLeadImportJob,
      downloadLeadImportTemplate,
      updateLeadImportExportStatusFilter,
      onLeadImportExportPageChange,
      onLeadImportExportSizeChange,
      createLeadImportFailedRowsExportJob,
      downloadLeadImportFailedRowsExportJob,
      isLeadImportActionPending,
      exportReportCsv,
      createExportJob,
      retryExportJob,
      downloadExportJob,
      retryReportExportJob,
      downloadReportExportJob,
      createReportDesignerTemplate,
      updateReportDesignerTemplate,
      runReportDesignerTemplate,
      saveLeadAssignmentRule,
      saveAutomationRule,
      changePermission,
      previewPermissionPack,
      commitPendingPack,
      rollbackPermissionRole,
      saveAdminUser,
      unlockAdminUser,
      getAdminUserError,
      inviteUser,
      createApprovalTemplate,
      submitApprovalInstance,
      updateApprovalTemplate,
      actApprovalTask,
      urgeApprovalTask,
      publishApprovalTemplate,
      rollbackApprovalTemplate,
      retryNotificationJob,
      toggleNotificationJob,
      toggleAllNotificationJobs,
      retryNotificationJobsByIds,
      retryNotificationJobsByFilter,
      createTenant,
      updateTenant,
      onPrefetch,
      onNavigate,
      trackWorkbenchEvent,
      buildWorkbenchFilterSignature,
      navigateToWorkbenchTarget,
      createQuoteFromOpportunity,
      viewOrdersFromOpportunity,
      createFollowUpShortcut,
      createTaskShortcut,
      urgeApprovalShortcut,
      copyPerfSnapshot,
      consumeQuotePrefill,
      refreshLeads,
      refreshCustomers,
      refreshPipeline,
      refreshFollowUps,
      refreshContacts,
      refreshContracts,
      refreshPayments,
      loadLeadAssignmentRules,
      loadAutomationRulesV1,
      loadAdminUsers,
    },
    approval: {
      loadApprovalDetail,
      loadApprovalTasks,
      loadApprovalTemplates,
      loadNotificationJobs,
    },
    leadImport: {},
    perf: {},
  })
  useRuntimePageModelSync({ ctx: pageModelCtx })
  const authShell = (
    <AuthShell
      auth={!hasAuthToken || isAuthRoute ? null : auth}
      locationPathname={location.pathname}
      apiContext={apiContext}
      lang={lang}
      setLang={setLang}
      t={t}
      navigate={navigate}
      submitLogin={submitLogin}
      loginForm={loginForm}
      setLoginForm={setLoginForm}
      formErrors={formErrors}
      setFormErrors={setFormErrors}
      submitSsoLogin={submitSsoLogin}
      ssoConfig={ssoConfig}
      ssoForm={ssoForm}
      setSsoForm={setSsoForm}
      oidcAuthorizing={oidcAuthorizing}
      startOidcLogin={startOidcLogin}
      loginError={loginError}
    />
  )
  const { showBootstrapping, showAuthShell } = useRuntimeAuthBranch({
    hasAuthToken,
    isAuthRoute,
    sessionBootstrapping,
    authShell,
  })
  if (showBootstrapping) {
    return <div className="app-bootstrapping">Loading session...</div>
  }
  if (showAuthShell) {
    return (
      <AppProviders apiContext={apiContext}>
        <Suspense fallback={<div className="app-bootstrapping">Loading shell...</div>}>
          {authShell}
        </Suspense>
      </AppProviders>
    )
  }

  return (
    <AppProviders apiContext={apiContext}>
      <Suspense fallback={<div className="app-bootstrapping">Loading shell...</div>}>
        <AppShell
          auth={auth}
          navGroups={navGroups}
          activePage={activePage}
          onNavigate={onNavigate}
          onPrefetch={onPrefetch}
          performLogout={performLogout}
          t={t}
          dev={import.meta.env.DEV && perfEnabledByQuery}
          perfMetrics={perfMetrics}
          currentLoaderKey={currentLoaderKey}
          lastRefreshReason={lastRefreshReason}
          currentPageSignature={currentPageSignature}
          currentSignatureHit={currentSignatureHit}
          recentWorkbenchJump={recentWorkbenchJump}
          domainLoadSource={domainLoadSource}
          copyPerfSnapshot={copyPerfSnapshot}
          lastPerfSnapshotAt={lastPerfSnapshotAt}
          markRenderCommit={markRenderCommit}
        />
      </Suspense>
    </AppProviders>
  )
}

export default AppRuntimeEngine
















