import { useMemo } from 'react'

export function useApprovalMapper(params) {
  const {
    role,
    approvalTemplateForm,
    setApprovalTemplateForm,
    approvalTemplates,
    setApprovalTemplates,
    updateApprovalTemplate,
    publishApprovalTemplate,
    rollbackApprovalTemplate,
    approvalTemplateVersions,
    loadApprovalTemplateVersions,
    approvalVersionTemplateId,
    approvalStats,
    approvalInstanceForm,
    setApprovalInstanceForm,
    createApprovalTemplate,
    submitApprovalInstance,
    approvalTasks,
    approvalInstances,
    approvalDetail,
    loadApprovalDetail,
    approvalTaskStatus,
    setApprovalTaskStatus,
    approvalOverdueOnly,
    setApprovalOverdueOnly,
    approvalEscalatedOnly,
    setApprovalEscalatedOnly,
    approvalActionComment,
    setApprovalActionComment,
    approvalTransferTo,
    setApprovalTransferTo,
    approvalActionResult,
    setApprovalActionResult,
    actApprovalTask,
    urgeApprovalTask,
    notificationJobs,
    notificationStatusFilter,
    setNotificationStatusFilter,
    notificationPage,
    notificationTotalPages,
    notificationSize,
    setNotificationPage,
    setNotificationSize,
    selectedNotificationJobs,
    toggleNotificationJob,
    toggleAllNotificationJobs,
    retryNotificationJob,
    retryNotificationJobsByIds,
    retryNotificationJobsByFilter,
    loadApprovalTasks,
    loadApprovalTemplates,
    loadNotificationJobs,
  } = params

  const mainApprovals = useMemo(() => ({
    template: approvalTemplateForm,
    setTemplate: setApprovalTemplateForm,
    templates: approvalTemplates,
    setTemplates: setApprovalTemplates,
    updateTemplate: updateApprovalTemplate,
    publishTemplate: publishApprovalTemplate,
    rollbackTemplate: rollbackApprovalTemplate,
    versions: approvalTemplateVersions,
    loadVersions: loadApprovalTemplateVersions,
    versionTemplateId: approvalVersionTemplateId,
    stats: approvalStats,
    instance: approvalInstanceForm,
    setInstance: setApprovalInstanceForm,
    createTemplate: createApprovalTemplate,
    submitInstance: submitApprovalInstance,
    tasks: approvalTasks,
    instances: approvalInstances,
    detail: approvalDetail,
    loadDetail: loadApprovalDetail,
    taskStatus: approvalTaskStatus,
    setTaskStatus: setApprovalTaskStatus,
    overdueOnly: approvalOverdueOnly,
    setOverdueOnly: setApprovalOverdueOnly,
    escalatedOnly: approvalEscalatedOnly,
    setEscalatedOnly: setApprovalEscalatedOnly,
    actionComment: approvalActionComment,
    setActionComment: setApprovalActionComment,
    transferTo: approvalTransferTo,
    setTransferTo: setApprovalTransferTo,
    actionResult: approvalActionResult,
    setActionResult: setApprovalActionResult,
    actTask: actApprovalTask,
    urgeTask: urgeApprovalTask,
    notifications: notificationJobs,
    notificationStatus: notificationStatusFilter,
    setNotificationStatus: setNotificationStatusFilter,
    notificationPage,
    notificationTotalPages,
    notificationSize,
    setNotificationPage,
    setNotificationSize,
    selectedNotificationJobs,
    toggleNotificationJob,
    toggleAllNotificationJobs,
    retryNotification: retryNotificationJob,
    retryNotificationByIds: retryNotificationJobsByIds,
    retryNotificationByFilter: retryNotificationJobsByFilter,
    reloadTasks: loadApprovalTasks,
    reloadTemplates: loadApprovalTemplates,
    reloadNotifications: loadNotificationJobs,
    canRetryNotifications: ['ADMIN', 'MANAGER'].includes(role),
  }), [
    approvalTemplateForm,
    setApprovalTemplateForm,
    approvalTemplates,
    setApprovalTemplates,
    updateApprovalTemplate,
    publishApprovalTemplate,
    rollbackApprovalTemplate,
    approvalTemplateVersions,
    loadApprovalTemplateVersions,
    approvalVersionTemplateId,
    approvalStats,
    approvalInstanceForm,
    setApprovalInstanceForm,
    createApprovalTemplate,
    submitApprovalInstance,
    approvalTasks,
    approvalInstances,
    approvalDetail,
    loadApprovalDetail,
    approvalTaskStatus,
    setApprovalTaskStatus,
    approvalOverdueOnly,
    setApprovalOverdueOnly,
    approvalEscalatedOnly,
    setApprovalEscalatedOnly,
    approvalActionComment,
    setApprovalActionComment,
    approvalTransferTo,
    setApprovalTransferTo,
    approvalActionResult,
    setApprovalActionResult,
    actApprovalTask,
    urgeApprovalTask,
    notificationJobs,
    notificationStatusFilter,
    setNotificationStatusFilter,
    notificationPage,
    notificationTotalPages,
    notificationSize,
    setNotificationPage,
    setNotificationSize,
    selectedNotificationJobs,
    toggleNotificationJob,
    toggleAllNotificationJobs,
    retryNotificationJob,
    retryNotificationJobsByIds,
    retryNotificationJobsByFilter,
    loadApprovalTasks,
    loadApprovalTemplates,
    loadNotificationJobs,
    role,
  ])

  return { mainApprovals }
}
