ALTER TABLE tenants ADD COLUMN market_profile VARCHAR(16) NOT NULL DEFAULT 'CN';
ALTER TABLE tenants ADD COLUMN tax_rule VARCHAR(32) NOT NULL DEFAULT 'VAT_CN';
ALTER TABLE tenants ADD COLUMN approval_mode VARCHAR(32) NOT NULL DEFAULT 'STRICT';
ALTER TABLE tenants ADD COLUMN channels_json VARCHAR(400) NOT NULL DEFAULT '["WECOM","DINGTALK"]';
ALTER TABLE tenants ADD COLUMN data_residency VARCHAR(40) NOT NULL DEFAULT 'CN';
ALTER TABLE tenants ADD COLUMN mask_level VARCHAR(32) NOT NULL DEFAULT 'STANDARD';

ALTER TABLE opportunities ADD COLUMN settlement_currency VARCHAR(16) NOT NULL DEFAULT 'CNY';
ALTER TABLE opportunities ADD COLUMN exchange_rate_snapshot VARCHAR(40) NOT NULL DEFAULT '1.000000@SYSTEM';
ALTER TABLE opportunities ADD COLUMN tax_display_mode VARCHAR(24) NOT NULL DEFAULT 'TAX_INCLUSIVE';
ALTER TABLE opportunities ADD COLUMN compliance_tag VARCHAR(32) NOT NULL DEFAULT 'STANDARD';

ALTER TABLE quotes ADD COLUMN settlement_currency VARCHAR(16) NOT NULL DEFAULT 'CNY';
ALTER TABLE quotes ADD COLUMN exchange_rate_snapshot VARCHAR(40) NOT NULL DEFAULT '1.000000@SYSTEM';
ALTER TABLE quotes ADD COLUMN invoice_status VARCHAR(24) NOT NULL DEFAULT 'NOT_REQUIRED';
ALTER TABLE quotes ADD COLUMN tax_display_mode VARCHAR(24) NOT NULL DEFAULT 'TAX_INCLUSIVE';
ALTER TABLE quotes ADD COLUMN compliance_tag VARCHAR(32) NOT NULL DEFAULT 'STANDARD';

ALTER TABLE order_records ADD COLUMN settlement_currency VARCHAR(16) NOT NULL DEFAULT 'CNY';
ALTER TABLE order_records ADD COLUMN exchange_rate_snapshot VARCHAR(40) NOT NULL DEFAULT '1.000000@SYSTEM';
ALTER TABLE order_records ADD COLUMN invoice_status VARCHAR(24) NOT NULL DEFAULT 'NOT_REQUIRED';
ALTER TABLE order_records ADD COLUMN tax_display_mode VARCHAR(24) NOT NULL DEFAULT 'TAX_INCLUSIVE';
ALTER TABLE order_records ADD COLUMN compliance_tag VARCHAR(32) NOT NULL DEFAULT 'STANDARD';

ALTER TABLE contracts ADD COLUMN settlement_currency VARCHAR(16) NOT NULL DEFAULT 'CNY';
ALTER TABLE contracts ADD COLUMN exchange_rate_snapshot VARCHAR(40) NOT NULL DEFAULT '1.000000@SYSTEM';
ALTER TABLE contracts ADD COLUMN invoice_status VARCHAR(24) NOT NULL DEFAULT 'NOT_REQUIRED';
ALTER TABLE contracts ADD COLUMN tax_display_mode VARCHAR(24) NOT NULL DEFAULT 'TAX_INCLUSIVE';
ALTER TABLE contracts ADD COLUMN compliance_tag VARCHAR(32) NOT NULL DEFAULT 'STANDARD';

ALTER TABLE payments ADD COLUMN settlement_currency VARCHAR(16) NOT NULL DEFAULT 'CNY';
ALTER TABLE payments ADD COLUMN exchange_rate_snapshot VARCHAR(40) NOT NULL DEFAULT '1.000000@SYSTEM';
ALTER TABLE payments ADD COLUMN invoice_status VARCHAR(24) NOT NULL DEFAULT 'NOT_REQUIRED';
ALTER TABLE payments ADD COLUMN tax_display_mode VARCHAR(24) NOT NULL DEFAULT 'TAX_INCLUSIVE';
ALTER TABLE payments ADD COLUMN compliance_tag VARCHAR(32) NOT NULL DEFAULT 'STANDARD';

UPDATE tenants
SET market_profile = COALESCE(NULLIF(TRIM(market_profile), ''), 'CN'),
    tax_rule = COALESCE(NULLIF(TRIM(tax_rule), ''), 'VAT_CN'),
    approval_mode = COALESCE(NULLIF(TRIM(approval_mode), ''), 'STRICT'),
    channels_json = COALESCE(NULLIF(TRIM(channels_json), ''), '["WECOM","DINGTALK"]'),
    data_residency = COALESCE(NULLIF(TRIM(data_residency), ''), 'CN'),
    mask_level = COALESCE(NULLIF(TRIM(mask_level), ''), 'STANDARD')
WHERE market_profile IS NULL
   OR tax_rule IS NULL
   OR approval_mode IS NULL
   OR channels_json IS NULL
   OR data_residency IS NULL
   OR mask_level IS NULL;
