export function buildReportingCtx(runtime) {
  return {
    auditLogs: runtime.auditLogs,
    setAuditLogs: runtime.setAuditLogs,
    reports: runtime.reports,
    setReports: runtime.setReports,
    workbenchToday: runtime.workbenchToday,
    setWorkbenchToday: runtime.setWorkbenchToday,
    exportJobs: runtime.exportJobs,
    setExportJobs: runtime.setExportJobs,
    exportJobsPage: runtime.exportJobsPage,
    setExportJobsPage: runtime.setExportJobsPage,
    exportJobsTotalPages: runtime.exportJobsTotalPages,
    setExportJobsTotalPages: runtime.setExportJobsTotalPages,
    exportJobsSize: runtime.exportJobsSize,
    setExportJobsSize: runtime.setExportJobsSize,
    exportStatusFilter: runtime.exportStatusFilter,
    setExportStatusFilter: runtime.setExportStatusFilter,
    reportExportJobs: runtime.reportExportJobs,
    setReportExportJobs: runtime.setReportExportJobs,
    reportExportJobsPage: runtime.reportExportJobsPage,
    setReportExportJobsPage: runtime.setReportExportJobsPage,
    reportExportJobsTotalPages: runtime.reportExportJobsTotalPages,
    setReportExportJobsTotalPages: runtime.setReportExportJobsTotalPages,
    reportExportJobsSize: runtime.reportExportJobsSize,
    setReportExportJobsSize: runtime.setReportExportJobsSize,
    reportExportStatusFilter: runtime.reportExportStatusFilter,
    setReportExportStatusFilter: runtime.setReportExportStatusFilter,
    autoRefreshJobs: runtime.autoRefreshJobs,
    setAutoRefreshJobs: runtime.setAutoRefreshJobs,
    autoRefreshReportJobs: runtime.autoRefreshReportJobs,
    setAutoRefreshReportJobs: runtime.setAutoRefreshReportJobs,
    reportDesignerForm: runtime.reportDesignerForm,
    setReportDesignerForm: runtime.setReportDesignerForm,
    designerTemplates: runtime.designerTemplates,
    setDesignerTemplates: runtime.setDesignerTemplates,
    designerRunResult: runtime.designerRunResult,
    setDesignerRunResult: runtime.setDesignerRunResult,
    auditUser: runtime.auditUser,
    setAuditUser: runtime.setAuditUser,
    auditRole: runtime.auditRole,
    setAuditRole: runtime.setAuditRole,
    auditAction: runtime.auditAction,
    setAuditAction: runtime.setAuditAction,
    auditFrom: runtime.auditFrom,
    setAuditFrom: runtime.setAuditFrom,
    auditTo: runtime.auditTo,
    setAuditTo: runtime.setAuditTo,
    auditRangeError: runtime.auditRangeError,
    setAuditRangeError: runtime.setAuditRangeError,
    reportOwner: runtime.reportOwner,
    setReportOwner: runtime.setReportOwner,
    reportDepartment: runtime.reportDepartment,
    setReportDepartment: runtime.setReportDepartment,
    reportTimezone: runtime.reportTimezone,
    setReportTimezone: runtime.setReportTimezone,
    reportCurrency: runtime.reportCurrency,
    setReportCurrency: runtime.setReportCurrency,
  }
}

export function buildLeadImportCtx(runtime) {
  return {
    leadImportJob: runtime.leadImportJob,
    setLeadImportJob: runtime.setLeadImportJob,
    leadImportJobs: runtime.leadImportJobs,
    setLeadImportJobs: runtime.setLeadImportJobs,
    leadImportStatusFilter: runtime.leadImportStatusFilter,
    setLeadImportStatusFilter: runtime.setLeadImportStatusFilter,
    leadImportPage: runtime.leadImportPage,
    setLeadImportPage: runtime.setLeadImportPage,
    leadImportTotalPages: runtime.leadImportTotalPages,
    setLeadImportTotalPages: runtime.setLeadImportTotalPages,
    leadImportSize: runtime.leadImportSize,
    setLeadImportSize: runtime.setLeadImportSize,
    leadImportFailedRows: runtime.leadImportFailedRows,
    setLeadImportFailedRows: runtime.setLeadImportFailedRows,
    leadImportMetrics: runtime.leadImportMetrics,
    setLeadImportMetrics: runtime.setLeadImportMetrics,
    leadImportExportJobs: runtime.leadImportExportJobs,
    setLeadImportExportJobs: runtime.setLeadImportExportJobs,
    leadImportExportStatusFilter: runtime.leadImportExportStatusFilter,
    setLeadImportExportStatusFilter: runtime.setLeadImportExportStatusFilter,
    leadImportExportPage: runtime.leadImportExportPage,
    setLeadImportExportPage: runtime.setLeadImportExportPage,
    leadImportExportTotalPages: runtime.leadImportExportTotalPages,
    setLeadImportExportTotalPages: runtime.setLeadImportExportTotalPages,
    leadImportExportSize: runtime.leadImportExportSize,
    setLeadImportExportSize: runtime.setLeadImportExportSize,
  }
}

export function buildPerfCtx(runtime) {
  return {
    perfMetrics: runtime.perfMetrics,
    setPerfMetrics: runtime.setPerfMetrics,
    lastPerfSnapshotAt: runtime.lastPerfSnapshotAt,
    setLastPerfSnapshotAt: runtime.setLastPerfSnapshotAt,
    currentLoaderKey: runtime.currentLoaderKey,
    setCurrentLoaderKey: runtime.setCurrentLoaderKey,
    lastRefreshReason: runtime.lastRefreshReason,
    setLastRefreshReason: runtime.setLastRefreshReason,
    currentPageSignature: runtime.currentPageSignature,
    setCurrentPageSignature: runtime.setCurrentPageSignature,
    currentSignatureHit: runtime.currentSignatureHit,
    setCurrentSignatureHit: runtime.setCurrentSignatureHit,
    recentWorkbenchJump: runtime.recentWorkbenchJump,
    setRecentWorkbenchJump: runtime.setRecentWorkbenchJump,
    domainLoadSource: runtime.domainLoadSource,
    setDomainLoadSource: runtime.setDomainLoadSource,
  }
}

export function buildPaginationCtx(runtime) {
  return {
    customerPage: runtime.customerPage,
    setCustomerPage: runtime.setCustomerPage,
    customerTotalPages: runtime.customerTotalPages,
    setCustomerTotalPages: runtime.setCustomerTotalPages,
    customerSize: runtime.customerSize,
    setCustomerSize: runtime.setCustomerSize,
    leadPage: runtime.leadPage,
    setLeadPage: runtime.setLeadPage,
    leadTotalPages: runtime.leadTotalPages,
    setLeadTotalPages: runtime.setLeadTotalPages,
    leadSize: runtime.leadSize,
    setLeadSize: runtime.setLeadSize,
    opportunityPage: runtime.opportunityPage,
    setOpportunityPage: runtime.setOpportunityPage,
    opportunityTotalPages: runtime.opportunityTotalPages,
    setOpportunityTotalPages: runtime.setOpportunityTotalPages,
    opportunitySize: runtime.opportunitySize,
    setOpportunitySize: runtime.setOpportunitySize,
    contactPage: runtime.contactPage,
    setContactPage: runtime.setContactPage,
    contactTotalPages: runtime.contactTotalPages,
    setContactTotalPages: runtime.setContactTotalPages,
    contactSize: runtime.contactSize,
    setContactSize: runtime.setContactSize,
    contractPage: runtime.contractPage,
    setContractPage: runtime.setContractPage,
    contractTotalPages: runtime.contractTotalPages,
    setContractTotalPages: runtime.setContractTotalPages,
    contractSize: runtime.contractSize,
    setContractSize: runtime.setContractSize,
    paymentPage: runtime.paymentPage,
    setPaymentPage: runtime.setPaymentPage,
    paymentTotalPages: runtime.paymentTotalPages,
    setPaymentTotalPages: runtime.setPaymentTotalPages,
    paymentSize: runtime.paymentSize,
    setPaymentSize: runtime.setPaymentSize,
  }
}

export function buildFormsCtx(runtime) {
  return {
    customerForm: runtime.customerForm,
    setCustomerForm: runtime.setCustomerForm,
    leadForm: runtime.leadForm,
    setLeadForm: runtime.setLeadForm,
    opportunityForm: runtime.opportunityForm,
    setOpportunityForm: runtime.setOpportunityForm,
    followUpForm: runtime.followUpForm,
    setFollowUpForm: runtime.setFollowUpForm,
    contactForm: runtime.contactForm,
    setContactForm: runtime.setContactForm,
    contractForm: runtime.contractForm,
    setContractForm: runtime.setContractForm,
    paymentForm: runtime.paymentForm,
    setPaymentForm: runtime.setPaymentForm,
    approvalTemplateForm: runtime.approvalTemplateForm,
    setApprovalTemplateForm: runtime.setApprovalTemplateForm,
    approvalInstanceForm: runtime.approvalInstanceForm,
    setApprovalInstanceForm: runtime.setApprovalInstanceForm,
    reportDesignerForm: runtime.reportDesignerForm,
    setReportDesignerForm: runtime.setReportDesignerForm,
    tenantForm: runtime.tenantForm,
    setTenantForm: runtime.setTenantForm,
    inviteForm: runtime.inviteForm,
    setInviteForm: runtime.setInviteForm,
    assignmentRuleForm: runtime.assignmentRuleForm,
    setAssignmentRuleForm: runtime.setAssignmentRuleForm,
    automationRuleForm: runtime.automationRuleForm,
    setAutomationRuleForm: runtime.setAutomationRuleForm,
  }
}
